### ISSUE TITLE
Exception when multiple OpenAPI services refrences is added in Visual Studio 2019 (swagger endpoints)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18204]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/842525/exception-when-multiple-openapi-services-refrences.html)._

---
I try to use the service reference OpenAPI in Visual Studio 2019, to generate clients based on existing swagger endpoints. It works fine when one endpoint is added, but multiple endpoints in different namespaces does not work. 
The reason is that the autogenerated APIException class is only generated in in the first "OpenApiReference". 
I tried to set the option "generateExceptionClasses" but it didn't have any effect.
Also tried to give the exception different names with the option "exceptionClass", but the exception class was only created in the first client.

This is the code that fails:
```
  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
      <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API1Client.cs</OutputPath>
    </OpenApiReference>
    <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
      <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API2Client.cs</OutputPath>
    </OpenApiReference>
  </ItemGroup>
```
It's possible to solve the problem with the following code, but I don't like to reference to  API1 in API2:

```
  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
      <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API1Client.cs</OutputPath>
    </OpenApiReference>
    <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
      <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API2Client.cs</OutputPath>
      <Options>/ExceptionClass:"API1. ApiException"</Options>
    </OpenApiReference>
  </ItemGroup>
```
Any way to slove this?

---
#### Visual Studio Feedback System on 12/5/2019, 00:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/6/2019, 01:28 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jeremysimmons** [comment]
Move `ApiException` and `ApiException<TResult>` to their own namespace

```
namespace Company.Api.Exceptions
{
  public partial class ApiException : System.Exception
  {
    ...
  }
  public partial class ApiException<TResult> : ApiException
  {
    ...
  }
}
```

Modify your csproj file OpenApiReference elements to include `      <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`

```
<ItemGroup>
    <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
      <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API1Client.cs</OutputPath>
      <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
    </OpenApiReference>
    <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
      <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
      <ClassName>{controller}Client</ClassName>
      <OutputPath>API2Client.cs</OutputPath>
      <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
    </OpenApiReference>
  </ItemGroup>
````

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by cloud-devlpr** [comment]
The ApiException error exists when generating two schemas:
The type or namespace name 'ApiException<>' could not be found (are you missing a using directive or an assembly reference?)

When will it be fixed?

**Comment by ryanbrandenburg** [comment]
Un-assigning myself as I'm no longer on that team. @mkArtakMSFT to triage this.

**Comment by jabak** [comment]
This should definitely be fixed ASAP.

**Comment by mwolford** [comment]
> Move `ApiException` and `ApiException<TResult>` to their own namespace
> 
> ```
> namespace Company.Api.Exceptions
> {
>   public partial class ApiException : System.Exception
>   {
>     ...
>   }
>   public partial class ApiException<TResult> : ApiException
>   {
>     ...
>   }
> }
> ```
> 
> Modify your csproj file OpenApiReference elements to include ` <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`
> 
> ```
> <ItemGroup>
>     <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
>       <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API1Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>     <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
>       <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API2Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>   </ItemGroup>
> ```

I am running into this problem also when having greater than 2 OpenAPI specs in a single Project.  I have them configured to use different Namespaces and different client names same

The above work around does work which gets me by for now but I would hope this gets resolved at some point.

**Comment by nZeus** [comment]
> > Modify your csproj file OpenApiReference elements to include ` <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`

Apparently order is also important, it has to be at the beginning of the options element, e.g:

`<Options>/AdditionalNamespaceUsages:Buddy.App.Services.OpenAPIs /GenerateExceptionClasses:false /UseBaseUrl:false /GenerateClientInterfaces:true /DateType:System.DateTime /DateTimeType:System.DateTime</Options>`

I wasted a lot of time trying to understand why it doesn't add additional namespace

**Comment by jbTim** [comment]
> Move `ApiException` and `ApiException<TResult>` to their own namespace
> 
> ```
> namespace Company.Api.Exceptions
> {
>   public partial class ApiException : System.Exception
>   {
>     ...
>   }
>   public partial class ApiException<TResult> : ApiException
>   {
>     ...
>   }
> }
> ```
> 
> Modify your csproj file OpenApiReference elements to include ` <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`
> 
> ```
> <ItemGroup>
>     <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
>       <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API1Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>     <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
>       <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API2Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>   </ItemGroup>
> ```

That fixed it for me as well but I also think that this can't be the solution... It should be fixed properly since this issues persists since more than two years now...

> > > Modify your csproj file OpenApiReference elements to include ` <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`
> 
> Apparently the order is also important, it has to be at the beginning of the options element, e.g:
> 
> `<Options>/AdditionalNamespaceUsages:Buddy.App.Services.OpenAPIs /GenerateExceptionClasses:false /UseBaseUrl:false /GenerateClientInterfaces:true /DateType:System.DateTime /DateTimeType:System.DateTime</Options>`
> 
> I wasted a lot of time trying to understand why it doesn't add additional namespace

For me the order didn't matter. I placed it at the end and it also worked.

**Comment by JsAndDotNet** [comment]
Hi Team.

This really is quite a big issue for users. 

The case for a microservice referencing more than one other microservice is very common, so a lot of people will encounter this (myself included).

Please can you re-triage it with this in mind?

**Comment by JsAndDotNet** [comment]
> Move `ApiException` and `ApiException<TResult>` to their own namespace
> 
> ```
> namespace Company.Api.Exceptions
> {
>   public partial class ApiException : System.Exception
>   {
>     ...
>   }
>   public partial class ApiException<TResult> : ApiException
>   {
>     ...
>   }
> }
> ```
> 
> Modify your csproj file OpenApiReference elements to include ` <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>`
> 
> ```
> <ItemGroup>
>     <OpenApiReference Include="OpenAPIs\api1Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API1">
>       <SourceUri>https://api1/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API1Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>     <OpenApiReference Include="OpenAPIs\api2Swagger.json" CodeGenerator="NSwagCSharp" Namespace="API2">
>       <SourceUri>https://api2/swagger/v1/swagger.json</SourceUri>
>       <ClassName>{controller}Client</ClassName>
>       <OutputPath>API2Client.cs</OutputPath>
>       <Options>/AdditionalNamespaceUsages:Ent.Api.Exceptions /GenerateExceptionClasses:false</Options>
>     </OpenApiReference>
>   </ItemGroup>
> ```

I had to create a different Exception class to get this to work:

```
namespace MyApp.OpenApi.Exceptions
{
    /// <summary>
    /// This is a fudge to get by for now
    /// https://github.com/dotnet/aspnetcore/issues/18204
    /// </summary>
    public partial class ApiException : System.Exception
    {
        public ApiException(string message, int statusCode, string? responseText, IReadOnlyDictionary<string, IEnumerable<string>> headers, Newtonsoft.Json.JsonException exception)
        {

        }
    }
    public partial class ApiException<TResult> : ApiException
    {
        public ApiException(string message, int statusCode, string? responseText, IReadOnlyDictionary<string, IEnumerable<string>> headers, Newtonsoft.Json.JsonException exception)
            : base(message, statusCode, responseText, headers, exception)
        {

        }
    }
}

```

Also note that `/AdditionalNamespaceUsages:Ent.Api.Exceptions`, the Ent.Api.Exceptions is not a copy and paster - you need to use your own namspace for the class you've created e.g. `MyApp.OpenApi.Exceptions`.

**Comment by filipreft** [comment]
IM baffled, this should be prioritized???

**Comment by werebear73-tritelph** [comment]
I saw this today

**Comment by krtek2k** [comment]
I am amazed how this is possible, that it is ignored and nobody solves it.
Multiple connected OpenApiReferences are refferencing the namespace of the first one; if it is swagger 2.0.
Which is a horrible solution.
And when it is openapi 3.0 it breaks completely between each other.

I had to also have those options in the first place of the OpenApiReference Options, it was not working otherwise.
I am shocked.

**Comment by krtek2k** [comment]
yes /GenerateExceptionClasses is no more allowed in net8.0
you have to use 

      <NSwagGenerateExceptionClasses>false</NSwagGenerateExceptionClasses>
      
it is still basically the same thing, just this option is not valid for net8.0 anymore.

**Comment by krtek2k** [comment]
cool, so basically "Example 3: Every client gets its own generated ApiException class (in different namespaces)." should be the case. Everything else is just a **WORKAROUND**

**Comment by krtek2k** [comment]
cool, so basically "Example 3: Every client gets its own generated ApiException class (in different namespaces)." should be the case. 
And this is a **MUST** when you are using a different namespaces.

**Comment by blogcraft** [comment]
It's a shame that this problem is still a thing after all these years...
