### ISSUE TITLE
Application Initialization *stops* working for .NET Core

### ISSUE THREAD

**Issue by Coruscate5** [dotnet/aspnetcore#19509]
### Describe the bug
Per https://github.com/dotnet/AspNetCore.Docs/issues/16675, there are scenarios when App Init stops working entirely for .NET Core processes.

Warmup.dll is loaded into IIS, and attempts to look for an endpoint at the website (e.g. if I tell it the preload URL is <site>/start, ProcMon reveals warmup searching for <Websitefolder>/start), but fails.

My intention is to run background tasks within the same .NET Core MVC project, which helps *enormously* with code consolidation, while maintaining responsibility separation.

### To Reproduce
Reproduction is difficult. I have several servers in which this behavior occurs, but it appears to only start happening after some period of time (publishing to the endpoint many times, Windows Updates in between, etc.).

Reinstalling IIS and registering App Init/.NET Core modules temporarily resolves the issue.

### Further technical details
I don't know what is needed to proceed - I can provide details of places where this continues to fail.

**Comment by Coruscate5** [comment]
Just FYI - this still happens with latest IIS and .NET Core - seems common, and basically invalidates existing MSFT docs that say this is a good option for background .NET Core services..

**Comment by unionthugface** [comment]
I just tried this guy's solution, and it worked for me, but I do not understand why it works: 

> In my case, lack of Garbage Collecting was making the problem. I traced the memory usage and it got increased by any page load. I just added this to my .csproj file:
> `  <PropertyGroup>
>     <ServerGarbageCollection>true</ServerGarbageCollection>
>     <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
>   </PropertyGroup>
> `
> and the problem got solved.

_Originally posted by @mobinseven in https://github.com/dotnet/aspnetcore/issues/11950#issuecomment-520295866_

Can anyone clue me in to any possible side effects from this?  For what it's worth I deployed this in my project on Friday, came in this morning, and my app ran successfully all weekend.  I can see in the logs that it is still shutting down, but then it starts right back up again, which is the behavior that I expect.

**Comment by Coruscate5** [comment]
@unionthugface  - This might explain some oddities, though complete lack of garbage collection seems like a top-priority sort of issue - is there a separate ticket for that? 

I had surmised that this problem was due to some bridge/integration issues between IIS and Kestrel, which if this solves would reinforce - I will try this out, as my temporary (aka until now permanent) solution has been to run a "start" call to the WebAPI on IIS every 5min to make sure the background services run..

**Comment by VSJames** [comment]
Is there an update on this? A year on and this problem still seems to be happening.  Is it potentially resolved in a later version of dotnet core? We've been relying on this working for a couple of years and we've got servers recently starting to display this behaviour.

**Comment by unionthugface** [comment]
[The garbage collection solution](https://github.com/dotnet/aspnetcore/issues/19509#issuecomment-683852466) is still to my knowledge the only way to "fix" this.  For what it's worth, I've had that "fix" running in a production environment for almost a year, have not had any issues.

**Comment by VSJames** [comment]
Thanks @unionthugface - I have also found today that this issue also manifests itself in another form.  We have a HTTP->HTTP redirect in place using a URL Rewrite in IIS.  It turns out that this seems to also kill the Application Initialization since it seems to use HTTP if it's an available binding before HTTPs.  I assume that the 'initialization' gets a redirect notice but doesn't follow that redirect.

Removing the URL rewrite and removing the HTTP (port 80) binding then brought the application initialization back into a functioning state.

**Comment by mohdali** [comment]
Is there still no solution for this issue? I have two servers, one is WS2016 while the other was cloned then upgraded to WS2019.

Initialization works in WS2016 but not in 2019. It is very frustrating as there is no clear clue why it is not.

**Comment by Coruscate5** [comment]
The Anonymous Authentication solution, it turns out, is the _only_ solution.

Apparently, Warmup.dll _requires_ the anonauth.dll to be used to register the app. I don't see any docs on this - can this be clarified in MSFT Background Service/IIS docs somewhere? Not sure the appropriate place

Proof: 

![image](https://user-images.githubusercontent.com/17749895/197641524-b6e9315e-982a-43e0-ac9d-aafd9b4dee6c.png)

**Comment by Coruscate5** [comment]
TBC, I can still use Windows auth in my .NET Core/Framework apps by just adding the authentication scheme in code. I just need to allow Anon Auth at the IIS level for this solution to work, which is does quite nicely.
