### ISSUE TITLE
Blazor Server Side Error: The list of component records is not valid, happens when close and reopen Browser with Continue where you left Setting On

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/aspnetcore#26174]
This issue was reported several times, but i think it was closed because of insufficient information.

Blazor Server Side (Net Core 3.1.8) displays Error Div with the console error " The list of component records is not valid" if you have set the browser to open every time the last page where you left, you close the browser and you reopen again .

This happens in development  mode (localhost) and in Production too (I have tested on Azure Virtual Machine windows 2019, IIS) on Every Browser : Edge, Chrome .

**How to Reproduce** 
- Check in Google Chrome from Settings / On startup: **Continue where you left off**
- Create a new Blazor Server Side Project & Run it
- Go to Counter Page, Click on Counter Button Several times 
- Close the Browser
- Open the Browser
**Obs**: Maybe Need to try more times, because sometimes the div error is not displayed .

I think this issue is related with another issue i have reported : https://github.com/dotnet/aspnetcore/issues/25951 . The idea is on mobile devices (my opinion) this option with : Settings / On startup: Continue where you left off comes by default at browsers and it is frustrating .

**We need some guidance how to solve this until "Next Sprint comes" ... We already want to put in production some projects and we are stuck at this .**

Maybe we can try with an Javascript Observer on Error Div , But there should be another condition where to check if this error happens only from this cause (The list of component records is not valid.) or check if Blazor is connected.....

```
var observerErr = new MutationObserver(function (mutations) {
            mutations.forEach(function (mutation) {
                if (mutation.attributeName == "style") {
                    var currentClassStateErr = mutation.target.style != null && mutation.target.style.display != null && mutation.target.style.display == 'block';                                      
                    if (currentClassStateErr && ONLY_ERROR_THE_listofcomponentrecordsisnotvalid)
                    {
                        location.reload();                            
                    }                     
                }
            });
        });       
observerErr.observe(elemToObserveEror, { attributes: true });
```

Please see the Image :

![CaptureError](https://user-images.githubusercontent.com/26578147/93879131-dd5f2f80-fce3-11ea-9f8c-ffabd5a6e557.JPG)

**Comment by SteveSandersonMS** [comment]
I think this is due to the browser reusing cached content when you don't want it to. The list of component descriptors encodes a timeout of 5 minutes, so if the browser tries to re-use the HTML after 5 minutes you will see this error.

I don't know why your initial HTML would be reused from browser cache, because with the default project template, the site won't return a HTTP header telling the browser to do that. Is it possible you've customized something that serves a cache control header?

Do you have a live deployed instance of your app that you could give a URL to? Then I could check for sure.

If not, you could check yourself by looking at the browser's *Network* tab in dev tools and looking for any `Cache-Control` header in the response for the initial HTML:

![image](https://user-images.githubusercontent.com/1101362/95445085-7fbf1a00-0956-11eb-9afc-b6d468c64987.png)

Notice `cache-control` under *response* headers (not *request* headers, which is different).

To tell the browser not to cache the response, could you try adding the following to your `_Host.chtml` page?

```cshtml
@{
    Response.Headers["Cache-Control"] = "no-store";
}
```

... and also check in the browser's network tab that it is sending `cache-control: no-store` in the response. Does this fix it?

**Comment by lucianparvu** [comment]
Hi,

I have sent this issue using the default template Blazor without any changes, as you can see in the First Post , as I described there . So maybe this error is not specific to our project .

You can check the next URL :  https://www.defaultnetcore3.siavmwebaz3.hostimpera.ro/en/laptops-tablets-phones/laptops-accessory/laptops-notebooks which is a template with the same structure with our project

Under Response Headers it is : strict-transport-security: max-age=5184000; includeSubDomains; preload

If we have settings for cache , the single point where can be is in Startup . Maybe we have something for cache control because we started this from NET Core 2, our old platform, not from Blazor Default Project .

We still have some settings for cache , but we use this on Controllers for example Like Sitemaps, but we don't use this in MapFallbackController .

```
 services.AddMvc().AddMvcOptions(options =>
            {
                options.CacheProfiles.Add("Sitemap",
                    new CacheProfile()
                    {
                        Duration = 300
                    });
                options.CacheProfiles.Add("FileHandler",
                   new CacheProfile()
                   {
                       Duration = 300,
                       Location = ResponseCacheLocation.Client
                   });
                options.CacheProfiles.Add("Never",
                    new CacheProfile()
                    {
                        Location = ResponseCacheLocation.None,
                        NoStore = true
                    });


            })
```

And for images we have this Type of Controllers where we need to Use Cache Headers (which helps for Search Engines) .
```
 public class FileHandlerController : Controller
    { 
       public async Task<IActionResult> ThumbnailProduct(int ID, string extension)
        {
            using (var scope = _ServiceProvider.CreateScope())
            {
                var context = scope.ServiceProvider.GetService<ApplicationDbContext>();
                try
                {
                    if (ID > 0 && !string.IsNullOrEmpty(extension))
                    {
                        var file = await context.ProductFiles.Where(p => p.ProductID == ID && p.IsPublished && p.ProductFileType.ProductFileTypeAction == ProductFileTypeAction.IsThumbnail)
                                                             .OrderBy(p=>p.Importance)
                                                             .Select(p => new ProductFile { ProductFileID = p.ProductFileID, Title = p.Title, ContentFile = p.ContentFile, Extension = p.Extension, LastUpdated = p.LastUpdated }).FirstOrDefaultAsync();
                        if (file != null)
                        {
                            byte[] contentFile = file.ContentFile;

                            if (file.IsImage)
                            {
                                _HttpContext.Response.Headers.Add("Last-Modified", file.LastUpdated.ToUniversalTime().ToString("R"));
                                _HttpContext.Response.Headers.Add("Expires", new[] { DateTime.UtcNow.AddDays(30).ToString("R") });
                                _HttpContext.Response.Headers.Add("ETag", file.LastUpdated.Ticks.ToString());
                                _HttpContext.Response.Headers.Add("Cache-Control", "max-age=31536000");
                                return File(contentFile, FileHelper.GetContentType(file.Extension));
                            }
                            else
                            {
                                return File(contentFile, FileHelper.GetContentType(file.Extension), file.UrlNice + file.Extension);
                            }
                        }
                    }
                }
                catch { }
                return RedirectToAction("ImageNotFound", "NotFound");
            }
        }
}
```

**Comment by SteveSandersonMS** [comment]
Thanks for confirming. Returning `Cache-Control: max-age=31536000` will definitely cause this problem, so you need to make sure you're not doing that on your `_Host.cshtml` responses (though you can do it on other responses if you want).

**Comment by lucianparvu** [comment]
Hi ,

I have checked and not .

Should be ? 

@{
    Microsoft.AspNetCore.Http.HttpContext.Response.Headers["Cache-Control"] = "no-store";
   }

Because: 

@{
    Response.Headers["Cache-Control"] = "no-store";
}

It is not recognised .

There is nothing about cache in HostController :

```
 public class HostController : Controller
    {       
        public readonly WebSiteSettings _Settings;
        WebsiteDBSettingService _WebsiteDBSettingService;       
        public IStringLocalizer<SharedResource> _SharedResource;
        public readonly ILogger _logger;
        public readonly BaseService _BaseService;
        public readonly IBackgroudJobService _BackgroudJobService;          

        public HostController(.... )
        {  ...         
                SharedResource = sharedResource;
        }
...
}
```

**Comment by lucianparvu** [comment]
We have tested meanwhile with Response.Headers["Cache-Control"] = "no-store" and now it works perfect in all major browsers in mobile and pc. So this issue is resolved.

Many Thanks

**Comment by Code-DJ** [comment]
You can also recreate this issue by duplicating a tab.

In Chrome/Edge, right-click on a tab and choose "Duplicate Tab". It shows the error bar at the bottom. Dev Tools shows "Error: The list of component records is not valid.".

I added the following to the top of _Host.cshtml and still have the same issue.
```
Response.Headers["Cache-Control"] = "no-store";
```

If you refresh the page, it loads it correctly. Then, close the tab and do the duplicate tab again, this time, it opens the new tab correctly.
