### ISSUE TITLE
CSS Isolation

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#26493]
### Describe the bug

There is a issue to apply the CSS Isolation when classes are added.
Below is the content of the index.razor file.

```
<EditForm EditContext="editContext">
    <InputText class="xxx" @bind-Value="Test.Response"/>
</EditForm>

@code {
    private Test Test { get; set; } = new Test();
    private EditContext editContext;

    protected override void OnInitialized()
    {
        editContext = new EditContext(Test);
    }
}
```

If the index.html file defines an index.css with the following style below, 
the input has a green background and the color of the font is red. It is fine.

```
.xxx {
    color: palevioletred;
    background-color: aquamarine;
}
```
![example2](https://user-images.githubusercontent.com/16502423/94829244-9b806880-040a-11eb-8f54-f7734414118c.png)
If the index.css is removed from the index.html file and the index.razor.css is added with the same definition
for the style, plus the reference of the _framework/scoped.styles.css, in the index.html file,
the input has no more a green background and the color of the font is not red. There is no index component. 
Is it normal ? 

![example](https://user-images.githubusercontent.com/16502423/94828041-5e67a680-0409-11eb-937a-34020a7728d6.png)

### Further technical details

ASP.NET Core 5.0 RC1
Google Chrome Version 85.0.4183.102 
Visual Studio 16.8.0 Preview 3.2
Blazor Web Assembly

**Comment by pranavkm** [comment]
@boukenka you'll need to tell the razor compiler to allow the scoped css styles can be allowed to be passed to the `InputText` component. 

```css
::deep .xxx {
    color: palevioletred;
    background-color: aquamarine;
}```

We're going to document this behavior as part of the css isolation documentation.

**Comment by boukenka** [comment]
@pranavkm Thank you for your prompt response. 
Unfortunately, the problem remains.
Does another modification need to be made?
![Example](https://user-images.githubusercontent.com/16502423/94850341-1788a980-0427-11eb-8a92-8ea7dec156c4.png)

**Comment by boukenka** [comment]
I have also tried the solution for the issue proposed by @SteveSandersonMS in https://github.com/dotnet/aspnetcore/issues/26137. Without success.

**Comment by SteveSandersonMS** [comment]
@boukenka Your application has not been correctly recompiled since you added the `::deep` modifier. I can tell this because your screenshot of the `.css` file in the browser tools shows that nothing has changed in the `.css` output (it's still using an unscoped style).

If you're using the RC1 framework, you may need to use the "Rebuild" command to make your change take effect. This is something we fixed in RC2, ensuring that a regular build produces correctly updated output.

**Comment by boukenka** [comment]
@SteveSandersonMS Thank your for the answer.
I have cleaned the solution and rebuild it. The problem remains (the browser cache is disabled)
It seems there is a problem with the index component. So I guess I have to wait for RC2 to get it fixed ?

![example](https://user-images.githubusercontent.com/16502423/94989651-b66feb80-0576-11eb-9f79-b566c89216e9.png)

**Comment by boukenka** [comment]
@pranavkm Could you please reopen this issue? At least, I can test if this is working when .NET 5 RC2 has been released and update this issue accordingly ?
