### ISSUE TITLE
Exception 'GetAuthenticationStateAsync was called before SetAuthenticationState.' thrown when calling AuthenticationStateProvider.GetAuthenticationStateAsync() method

### ISSUE THREAD

**Issue by AFAde** [dotnet/aspnetcore#28684]
### Describe the bug
In my Blazor Server app, exactly as described in this bug report, 

['GetAuthenticationStateAsync was called before SetAuthenticationState.'](https://github.com/dotnet/aspnetcore/issues/17442)

the GetAuthenticationStateAsync works only if the AuthenticationStateProvider service is synchronously called from a Blazor page. 

In any async call running in the background it fails with the mentioned error message.

### To Reproduce
Here is a sample repo:
[BlazorAppWithAuthenticationError](https://github.com/AFAde/BlazorAppWithAuthenticationError)

Just start the application and click on Fetch Data, the exception will be thrown immediately at the line 23 of the AuthTokenHandler class. I am using the HttpClient Factory  pattern, which seems to lead to the issue.

### Exceptions (if any)

```
System.InvalidOperationException: GetAuthenticationStateAsync was called before SetAuthenticationState.
   at Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider.GetAuthenticationStateAsync()
   at MyClasss.ExecuteAsync
...

```

### Further technical details
- ASP.NET Core version 5
-  output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 16.8.3

**Comment by beausmyth1990** [comment]
I am also getting this issue and I cannot, for the life of me, figure out why. If I inject AuthenticationStateProvider via construction injection into any service and make a call to GetAuthenticationStateAsync() at any point in my code it will throw the exception mentioned by @AFAde. This will even occur when the user is logged-in, so I know that an the AuthenticationState must exist. Any thoughts on what the problem could be?

**Comment by maxxhount** [comment]
Im getting the same issue. Any update?

**Comment by shareonline** [comment]
Same.. Blazor Server side on .NET 5.
Trying to use in a userService together with EF Core and it is periodically failing

**Comment by vavdb** [comment]
var authUser = _consentHandler.User;
            var accessToken = await _tokenAcquisition
                .GetAccessTokenForUserAsync(_scopes, user: authUser)
                .ConfigureAwait(false);

**Comment by cuperman007** [comment]
I'm hitting same issue. I am using Azure AD for my logins. I have a generic repository pattern where I want to automatically add the current user name to a `LastEditedBy` field on all records when they are saved.

When injecting `AuthenticationStateProvider` into the service class,  I get the error when calling the `GetAuthenticationStateAsync` method.

Many resources suggest using `IHttpContextAccessor`, but this does not work with Azure app service and we are advised not to use [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state)

Is there another suitable work around to access the current user name in a service?

**Comment by FelipeCostaGualberto** [comment]
I'm also having this problem, I can't inject `AuthenticationStateProvider` in my services.
Blazor Server Side with ASP.NET 5.

**Comment by mikaelservin** [comment]
I have been developing a Blazor Server application for a few weeks now and tried to add a UserService where I can get the signed in user's identity and all post say you should use AuthenticationStateProvider injected to the service. I tried that but keep getting the error that I first should call SetAuthenticationState. 

Is there really no work around for this? Is there any other way to get the identity or username for the signed in user that is possible to use in a service? The UserId is shown in the LoginDisplay component where @context.User.Identity.Name! is used.

**Comment by ericjohnston** [comment]
I'm having the same type of issue in a Blazor Server app when trying to use the information from a service by injecting AuthenticationStateProvider.  The only workaround I've been able to work out is to use both IHttpContextAccessor and the AuthenticationStateProvider.  It's not recommended nor ideal, but it mostly works.

I'm using the IHttpContextAccessor in middleware to set the properties I need on scoped objects that are injected into the service(s), but I'm using AuthenticationStateProvider in Blazor components, as recommended, where the HttpContext is already disposed.

It definitely feels very hacky and I'm sure it could be done in a much more elegant way than my implementation, but it's what works for now.

I'm assuming this issue impacts anyone building a Blazor Server app that needs user state/context information outside of Blazor components.

**Comment by Panzerfury** [comment]
I think this should be a priority.

**Comment by mikaelservin** [comment]
Thanks @ericjohnston for the reply. I will try and do something with IHttpContextAccessor even though I understand that it's not recommended. I am new to Blazor and .Net 5 and I am learning the hard way that things don't always work the way I think they should. I spent a couple of hours on this before I found this issue and understood that it was a bug and not something I was doing wrong again.

I hope there is a fix on the way for this and I think someone should write an official work around in the documentation so that people don't have to invent their own solutions.

**Comment by beausmyth1990** [comment]
> I'm having the same type of issue in a Blazor Server app when trying to use the information from a service by injecting AuthenticationStateProvider. The only workaround I've been able to work out is to use both IHttpContextAccessor and the AuthenticationStateProvider. It's not recommended nor ideal, but it mostly works for my use case.
> 
> I'm using the IHttpContextAccessor in middleware to set the properties I need on scoped objects that are injected into the service(s), but I'm using AuthenticationStateProvider in Blazor components, as recommended, where the HttpContext is already disposed.
> 
> It definitely feels very hacky and I'm sure it could be done in a much more elegant way than my implementation, but it's what works for now.
> 
> I'm assuming this issue impacts anyone building a Blazor Server app that needs user state/context information outside of Blazor components.

I believe that it has been mentioned (somewhere in the Docs) that IHttpContextAccessor should NOT be used. Reason being - they might remove it in later versions, and not to mention that Server-Side only uses HTTP to initiate a web socket connection - it's a completely different protocol of communication. Once the socket is open no more HTTP. I fear that this is not a viable workaround. We need this issue addressed - like now.

**Comment by shareonline** [comment]
> > I'm having the same type of issue in a Blazor Server app when trying to use the information from a service by injecting AuthenticationStateProvider. The only workaround I've been able to work out is to use both IHttpContextAccessor and the AuthenticationStateProvider. It's not recommended nor ideal, but it mostly works for my use case.
> > I'm using the IHttpContextAccessor in middleware to set the properties I need on scoped objects that are injected into the service(s), but I'm using AuthenticationStateProvider in Blazor components, as recommended, where the HttpContext is already disposed.
> > It definitely feels very hacky and I'm sure it could be done in a much more elegant way than my implementation, but it's what works for now.
> > I'm assuming this issue impacts anyone building a Blazor Server app that needs user state/context information outside of Blazor components.
> 
> I believe that it has been mentioned (somewhere in the Docs) that IHttpContextAccessor should NOT be used. Reason being - they might remove it in later versions, and not to mention that Server-Side only uses HTTP to initiate a web socket connection - it's a completely different protocol of communication. Once the socket is open no more HTTP. I fear that this is not a viable workaround. We need this issue addressed - like, now.

THIS.. Using the exact same method, and if not recommended or supported we truly need a fix as quick as possible..
It needs to move a little faster with stuff like this in Blazor, if it is to become a mainstream framework. Don't get me wrong development is fast for Blazor and I love it in general, but key issues like this hinders all "real" development that isn't just front pages for companies.

**Comment by beausmyth1990** [comment]
@shareonline I performed a quick test today by whipping-up a new Blazor Server-Side proj and injecting the AuthenticationStateProvider into a Scoped service. After calling the GetAuthenticationAsync method of the AutheticationStateProvider I did not get an exception. Could it be that this problem has been solved? Was the fix released in .Net 5? Who knows.

**Comment by shareonline** [comment]
> @shareonline I performed a quick test today by whipping-up a new Blazor Server-Side proj and injecting the AuthenticationStateProvider into a Scoped service. After calling the GetAuthenticationAsync method of the AutheticationStateProvider I did not get an exception. Could it be that this problem has been solved? Was the fix released in .Net 5? Who knows.

Hmm yeah maybe..
I have only run into the errors when using it with my scoped EF context.
I have solved it by using a transient dbcontext and a scoped service for my userservice. The userservice lives in my frontend project, where my dbcontext lives in my shared/service project. This works and so far so good.

**Comment by AFAde** [comment]
> 
> 
> @shareonline I performed a quick test today by whipping-up a new Blazor Server-Side proj and injecting the AuthenticationStateProvider into a Scoped service. After calling the GetAuthenticationAsync method of the AutheticationStateProvider I did not get an exception. Could it be that this problem has been solved? Was the fix released in .Net 5? Who knows.

I am using .NET 5 and definitely this issue has not been solved, I can still reproduce the error

**Comment by agilenut** [comment]
This issue is still occurring when injecting AuthenticationStateProvider into a DelegatingHandler with latest .Net 5.

We really need a consistent way to get access to the user context. It is silly to have to do one thing when we are in Blazor land and another thing when we have a full HttpContext. 

Status or workaround?

**Comment by setezerocinco** [comment]
Any news about this problem?

**Comment by Christoffleroux** [comment]
Any new updated?

**Comment by MihaMarkic** [comment]
I can't understand how this issue doesn't have a bigger priority and how it wasn't solved in a year. Even worse, tagging it as .NET 7 or Backlog. This isn't an UI annoyance, it's a bit more important don't you think so?

**Comment by appsupport-gc** [comment]
I thought this would get FIXED in dotnet 6.0!!  this is Terrible!!

**Comment by aradhaghi** [comment]
Anu update here? Blazor Server should not be called "Production Ready" unless this is resolved! I can't understand how this is not urgent? a few examples on why this is important:
- User Context Service 
- Add User Context to EF dbcontext and apply global filter queries for multi-tenancy

**Comment by JoeGER94** [comment]
Does anyone have a solution/workaround for this?

**Comment by JoeGER94** [comment]
Thanks for your fast feedback. It's quite frustrating if you try to setup a multi-user-system.
Maybe we can pray for @SteveSandersonMS  to do something or even to give feedback to us

**Comment by appsupport-gc** [comment]
Yes I created a process where I add in the access token to the HTTPClient every time I instantiate it using my own custom token provider class which depends upon AuthenticationStateProvider.  I heard the issue has to do with HTTPClientFactory so perhaps avoiding that would work as well not sure. I can post my solution if helpful but it might be a few weeks.

**Comment by Gibrid89** [comment]
Having the same problem in DBContext

**Comment by SadPraetor** [comment]
One scenario where I'm encountering this issue consistently, if you call for AuthenticationState from created scope. You create a separate scope in your code, and somewhere under this scope you call `GetAuthenticatonStateAsync` . 
One way to figure out if this is your situation, is to register `AuthenticatonStateProvider` as singleton (just for this test), if it works fine as singleton, but it fails if it is registered as scoped, that would be a strong indication you are doing this mistake.

**Comment by raphael-theriault** [comment]
For what it's worth.. I fix my problem with a try/catch, as the problematic method was called multiple times.
Quick explanation :
1- Set a claim.
2- try to read it

Here is the scenario for my bug, hopefully someone will tell me a better way to fix it.
using Blazor server , ,net 7.

Step 1: set custom Claim "TennantId" here : 

```
MyUserClaimsPrincipalFactory.CreateAsync(Myuser user) - MyUser is a derived class of IdentityUser
{
   ...
  string guid = GetTheGuid();
                ((ClaimsIdentity)principal.Identity).AddClaims(new[] {
                    new Claim("TennantId", guid)
                });
...
}
```
Then, in my dbContext I set the global filtering from my TenantId, in 
'''
 protected override void OnModelCreating(ModelBuilder modelBuilder)`
{
...
 entities = ModelBuilderEntityFinder.GetEntityBaseTenantOwned(modelBuilder);

        if (entities != null)
        {
            Expression<Func<EntityBaseTenantOwned, bool>> filterExpr = bm => !bm.IsDeleted && bm.TenantId == TenantService.GetTenant();
            foreach (var entity in entities)
            {
                modelBuilder.Entity(entity.ClrType).HasQueryFilter(GenerateLambda<EntityBaseTenantOwned>(entity, filterExpr));
            }
        }
...
'''

where TenantService.GetTenant() is 
'''
 public Guid GetTenant()
        {
            Guid ret = Guid.Empty;
            try
            {
                var auth = Task.Run(() => authenticationStateProvider.GetAuthenticationStateAsync()).Result;

                var user = auth.User;
                if (user.Identity.IsAuthenticated)
                {
                    var claims = user.Claims;
                    string str = user.FindFirst(a => a.Type == "TennantId")?.Value;
                    if (str != null)
                        ret = Guid.Parse(str);
                }
            }
            catch(Exception)
            {
               
            }

            return ret;
            
        }

'''

the fact that I have bring a try/catch in GetTenant() have "fixed it". Because it's called multple times, and the only time the error throes, is when the first call is made.  All the other calls are OK. 
The way I see it, it is highly prompt to futur error and I am still playing with it.  But for the moment, nothing seems to explode... Would love a beter fix.

**Comment by appsupport-gc** [comment]
Good Question!!

**Comment by javiercn** [comment]
This is currently documented [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-7.0#access-blazor-services-from-a-different-di-scope)

**Comment by javiercn** [comment]
@pilcherd the example I provided also works for this.

You can't call AuthenticationStateProvider directly within HttpClientFactory because it creates its own scope for the handlers. The way this is handled is by creating a handler that reads from an async local and having the code that calls into the HttpClient instance set that async local with the right context before the call.

This is also how it works in ASP.NET Core for things like header propagation, where the HeaderPropagationMiddleware sets the context. https://github.com/dotnet/aspnetcore/tree/main/src/Middleware/HeaderPropagation/src

**Comment by cedwards-telis** [comment]
@javiercn maybe submit a pull request to the OP's repo so we can see how we are supposed to implement this?

**Comment by AFAde** [comment]
Hi @javiercn , thanks a lot. By following your suggestions I was able to get the code working.  If I get it right, when using pattern like the HttpClientFactory each control needs to inherit from CustomComponentBase, is this right?

One more: if I want to decouple pages/controls the from the core logic - for example, by following the MVVM architectural design pattern - what would be the best approach? In other words, is it possible to decouple the initialization and handling of the BlazorContextAccessor from the control? If yes, how? do you have any sample? 


For those who are interested, you can take a look at the repository from the top of this thread, I just pushed the changes.

**Comment by javiercn** [comment]
> One more: if I want to decouple pages/controls the from the core logic - for example, by following the MVVM architectural design pattern - what would be the best approach? In other words, is it possible to decouple the initialization and handling of the BlazorContextAccessor from the control? If yes, how? do you have any sample?

There's not a great way of doing this in a centralized way, but that's something we might change in .NET 8.0 as part of 
https://github.com/dotnet/aspnetcore/issues/30287
