### ISSUE TITLE
Net Core 6 Blazor Server Hot Reload is Slow for Big Projects

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/aspnetcore#32867]
Hi,

I have a project Blazor Server with ~ 180 .razor Files (186 Files, 55 Folder)

If all folder structure is in the same project the hot reload takes ~ 15 seconds , more than build time ( 10 seconds ) .

If we split the .razor files on Libraries , we get the next Results

Main App (Only Host.razor) : (Reference to Shared Library, Front Library,Admin Library )
– Hot Reload for all tests after 1 seconds

Shared Library (21 Files, 1 Folder) : Layout, Shared Components, etc
– Add p: Hot Reload after 2-3 seconds
– Add style to p : Hot Reload after after 2-3 seconds
– Counter Example with ++ : Hot Reload after 1 seconds

Front Library (54 Files, 15 Folders) (Reference to Shared Library)
– Add p: Hot Reload after 20 seconds
– Add style to p : Hot Reload after after 4 seconds
– Counter Example with ++ : Hot Reload after 3 seconds

Admin Library (106 Files, 36 Folders) (Reference to Shared Library)
– Add p: Hot Reload after 12 seconds
– Add style to p : Hot Reload after after 8 seconds
– Counter Example with ++ : Hot Reload after 8 seconds

I am suspecting  maybe we have something from old Projects because we have upgraded from 2.2 to 3.1 ( Blazor ) to 5,etc

We have tried to remove html from Some razor Files specially Layout and seems to work quickly if there is just some simple html lines.

How can we improve ? It depends on File nr and complexity ? or depends on references ? How can we structure the project ?

PS: The issue is posted based on disscussion : https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/comment-page-3/#comment-3245

**Comment by pranavkm** [comment]
> I am suspecting maybe we have something from old Projects because we have upgraded from 2.2 to 3.1 ( Blazor ) to 5,etc

To confirm, is the project you’re running a .NET 6 preview project?

**Comment by lucianparvu** [comment]
Yes, right now I have installed Visual Studio Preview and Net Core 6 Preview.

Please find  the Project Description
```
 
<Project Sdk="Microsoft.NET.Sdk.Web">		 
	<PropertyGroup> 	 	 
	 <TargetFramework>net6.0</TargetFramework> 		 
		<ServerGarbageCollection>false</ServerGarbageCollection> 			
	</PropertyGroup>		
	<ItemGroup>	 
		<PackageReference Include="AspNet.Security.OAuth.Apple" Version="5.0.4" /> 		 
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="6.0.0-preview.3.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0-preview.3.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BlazorDateRangePicker" Version="3.5.0" />
		<PackageReference Include="Blazored.LocalStorage" Version="3.0.0" />
		<PackageReference Include="Blazored.SessionStorage" Version="1.0.13" />
		<PackageReference Include="BlazorInputFile" Version="0.2.0" />
		<PackageReference Include="Bower" Version="1.3.11" />
		<PackageReference Include="ChartJs.Blazor" Version="1.1.0" />
		<PackageReference Include="EPPlus" Version="5.6.2" />	
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />	
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
		<PackageReference Include="Hangfire" Version="1.7.22" />
		<PackageReference Include="MailKit" Version="2.11.1" />	 
		<PackageReference Include="SixLabors.ImageSharp" Version="1.0.3" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\BLL\BLL.csproj" />
	  <ProjectReference Include="..\DAL\DAL.csproj" />
	  <ProjectReference Include="..\SL\SL.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="AuthKey_9G5GG557T4.p8">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	<ProjectExtensions><VisualStudio><UserProperties wwwroot_4lib_4bootstrap_4dist_4css_4bootstrap_1min_1css_1map__JsonSchema="" /></VisualStudio></ProjectExtensions>
</Project> 
```

**Comment by oiBio** [comment]
I also can confirm this.
i just tested hotreload on our large project (~ 180 *.razor files) and a simple change also needs about 10-15 seconds.
i did not look any futher into this, we are waiting for a better user experiance on visual studio (dotnet watch run is meh)

we also migrated the project from the first blazor preview to net6

**Comment by pranavkm** [comment]
Thanks for the issue report. Right now, the source generator for Razor has a stop-gap caching solution in place which works poorly in large apps. That's cause hot reload to perform more work than necessary resulting in the poor performance. 

We think some [new compiler features](https://github.com/dotnet/aspnetcore/issues/31244) that we plan to use by 6.0-preview6 as well as some tactical perf improvements we're also landing in the same release should improve things.

That said, in my demo app with about 200 files, I was seeing ~1 second update times. The time is primarily influenced by the time taken to parse Razor code, so it's entirely possible that 10-15 second delays you are seeing is result of a more sophisticated app. But if you're willing to share you app, I could make sure that's the root cause here and not something more nefarious. A GitHub repo works great, but if are willing to share your apps privately, we can work out something for that too.

**Comment by lucianparvu** [comment]
Yes, after more tests it depends more on razor complexity . Maybe we can refactor, but we need to know what thinks we should refactor .

We can give access to a virtual machine with Visual Studio in Azure Cloud in private. How can i contact you in private ?  My Email Address: lucian.parvu@softimpera.ro ( Works on Teams too for chat ).

**Comment by pranavkm** [comment]
> We can give access to a virtual machine with Visual Studio in Azure Cloud in private

It might be a bit tricky to do work on a VM without my tools installed. That said, we've started work on the compiler feature that should speed things up here and expect to be done with it in our preview6 release. How about we have you try it out as soon that's checked in? We'd be happy to investigate further if you continue seeing slow results with that change.

FYI @captainsafia

**Comment by lucianparvu** [comment]
Thank's it is ok .

**Comment by pranavkm** [comment]
Verified this using RC1 bits. For a an app with about 500+ razor files (https://github.com/pranavkm/LargeRazorApp), here's what we get:

* The first edit is about as expensive as a cold start build
* Consecutive edits take about 600ms each and most of that is spent in the compiler / producing the deltas etc. We think that's a good place to be for 6.0.

### Raw numbers

Cold start build:
```
> dotnet build --no-restore
Time Elapsed 00:00:06.71
```

First edit
```
watch : File changed: D:\temp\watchapps\LargeRazorApp\Pages\Index.razor. 
watch : Received successful apply from delta applier.
watch : Hot reload of changes succeeded.
watch : Hot reload change handled in 5583.391ms.
```

Consequent edits:
```
watch : File changed: D:\temp\watchapps\LargeRazorApp\Pages\Index.razor.
watch : Received successful apply from delta applier.
watch : Hot reload of changes succeeded.
watch : Hot reload change handled in 628.0315ms.

watch : File changed: D:\temp\watchapps\LargeRazorApp\Pages\Counter.razor.
watch : Received successful apply from delta applier.
watch : Hot reload of changes succeeded.
watch : Hot reload change handled in 525.4524ms.

watch : File changed: D:\temp\watchapps\LargeRazorApp\Pages\Index.razor.
watch : Received successful apply from delta applier.
watch : Hot reload of changes succeeded.
watch : Hot reload change handled in 516.9593ms.
```

@lucianparvu feel free to give hot reload a try using a preview7 or rc1 SDK (https://github.com/dotnet/installer#installers-and-binaries) and let me know if the experience is any better.

**Comment by oiBio** [comment]
i tried 6.0.100-preview.7.21379.14 with my project and the timings are much better. i see changes in less than 1 second.
good work!

**Comment by lucianparvu** [comment]
Hi,

I am unable to test it . Because I can't run the app,  because I get Error :
InvalidOperationException: The view '_Host' was not found. The following locations were searched:
/Views/Host/_Host.cshtml
/Views/Shared/_Host.cshtml
/Pages/Shared/_Host.cshtml

Something has Changed ?

Steps:

- Upgrate project from 5 to : 

<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0-rc.1.*"/> 
<PackageReference Include="AspNet.Security.OAuth.Apple" Version="5.0.4" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.0-rc.1.*" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="6.0.0-rc.1.*" />

- I have updated The Visual Studio Preview to the latest version 

- I have installed Release/6.0.1XX-preview7 (6.0.x Runtime) x64 and x86 on Windows from here https://github.com/dotnet/installer#installers-and-binaries

I am using :

endpoints.MapBlazorHub(); 
endpoints.MapFallbackToController("_Host", "Host");

**Comment by DamianEdwards** [comment]
@lucianparvu are you able to provide an example of the .razor files that cause these times? Also it seems your mixing a preview.7 tooling/runtime (SDK) with rc.1 packages. That shouldn't matter too much for this scenario, but I'd be interested in what times you get using rc.1 tooling/runtime (SDK).

**Comment by lucianparvu** [comment]
> @lucianparvu are you able to provide an example of the .razor files that cause these times? Also it seems your mixing a preview.7 tooling/runtime (SDK) with rc.1 packages. That shouldn't matter too much for this scenario, but I'd be interested in what times you get using rc.1 tooling/runtime (SDK).

Yes, Please Find Here: https://github.com/lucianparvu/Files.git

FrontLayout.razor
FrontDepartment.razor

For example if remove a few Edit Forms from Front Department , or some complex foreach from Front Layout i can see the time improving .

Of course, we can do a lot of refactoring, more components, etc, but we need to know if is necessary or need to know how hot reload works.

Thank's

**Comment by pranavkm** [comment]
@lucianparvu could I bother you to try out the rc2 builds of the SDK? We made some changes to Razor's source generator in that release which appears to make a big dent in the time it takes to perform edits with one of the larger projects we've been using. rc2 builds of the installer are available at https://github.com/dotnet/installer#installers-and-binaries under the `Release/6.0.1XX (6.0.x Runtime)` column.

**Comment by DamianEdwards** [comment]
Direct link to rc.2 build Windows x64 SDK installer: https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe

**Comment by En3Tho** [comment]
Had the same issue in #35452. If you want to try rc1 you have to upgrade Razor.DynamicCompilation package and all packages that are linked to it to rc1. Otherwise it's a no-go. Happened between preview 7 and rc1.

**Comment by lucianparvu** [comment]
Hello,

You can bother me to test it, i am interested to make hot reload works.

I have installed the RC2 build and Visual studio 2022 . 

Because of the issue with  #35452 (The view '_Host' was not found) i had to add services.AddControllersWithViews().AddRazorRuntimeCompilation(); Don't know if is correct

I can run the project only in Visual studio 2022, in 2019 i still get that error .

If run the project with dotnet watch :

- If add some html tags `<p>test</p>` at the middle or the beginning of the razor File , the hot reload takes 40 seconds to 1-2 minutes and sometimes never get response.
- If add some html tags at the end (before )@code {...} the hotreload takes 2-3 seconds
- If add some style to an existing html tag `<p style="color:red">test3</p>` the hot reload takes ~2-3 seconds
- If i change the CSS File from the FrontLayout.razor.css  (CSS isolated file) the hot reload is instant but need to hit Ctrl-F5 in browser to see changes
- Counter Example : hot reload takes 5 seconds

`<button @onclick="@(()=>{Counter=Counter+2;})">V1</button> 
 	 <p>@Counter</p>`

- For this Counter version , seems to be instant :
 ```
<button @onclick="@ounterClick">V1</button> 
  void CounterClick()
    {
         Counter=Counter+6; 
    }
```

**Comment by pranavkm** [comment]
@lucianparvu the missing view bit is expected in VS 2019. Razor relies on new compiler features that are only available in VS 2022. You shouldn't need runtime compilation with the VS 2022 though

> If add some html tags <p>test</p> at the middle or the beginning of the razor File , the hot reload takes 40 seconds to 1-2 minutes and sometimes never get response.

Is that persistent, or only for the first edit? I've also observed this issue with dotnet-watch where the first edit takes fairly long.

**Comment by lucianparvu** [comment]
Hello,

It seems to see persistent, doesn't matter if the is first edit or not.

I have recorded my screen , please see here on youtoube: https://youtu.be/rKo6sePs4Uo

**Comment by MiheevN** [comment]
I love you. But ... There are just thoughts:

I have already received the release version of VS 2022 and, accordingly, .Net 6, but for half a year the update rate has not changed ...

On a template project, this takes 1 second in Medium.
And on a large working project AT LEAST at least Not less than the time of a complete reboot.
The rest of the code is constantly checked for changes ...
As if for some reason he scans the whole project every time. Why... 😥

I have a Threaropper with 24 cores, but VS usually doesn't load more than 5% of the CPU.
Let it use at least 100%, but it can be done faster.👿
And at the bottom left of the tasks, it is clearly written that the LOW task is happening.
But It should be the highest priority, because the quick update of the code is the primary task.

And if you make a change that is unacceptable, or make a mistake, then Itellisense will hang without highlighting it, and HotReload will never change anything again. And he does not report it.
At the same time, it will continue to load something heavily.

**Comment by saascentral** [comment]
Also just downloaded released version of VS 2022 and tested hot reload on our current project, .net 6.0 and have around 150+ pages (.razor and code behind files). It consistently took 20-25 seconds to for the updates to get sent to the browser.

**Comment by oiBio** [comment]
We do have the same issue in our project. Current work around is to use "dotnet watch" which is pretty fast (1-2 seconds) 
see: https://developercommunity.visualstudio.com/t/Hot-Reload-in-VS-very-slow-but-fast-wit/1563649

**Comment by zerox981** [comment]
Same  here.  For one project running with VS 2022 (Debugging or Start without debugging) is slow ~8-10s and dontnet watch takes ~1-2s. Other project takes ~8-12s every time (also with dotnet watch) until the changes are applied/visible. Both have similar architecture, the second one is larger and has a bit more projects in the solution. All projects and libraries are upgraded to .net 6.

**Comment by saascentral** [comment]
@zerox981 @oiBio  you're right. I tried it with dotnet watch on the same project where hot reload on VS took 20-25s, dotnet watch takes ~1-2s tops. I was hoping VS 2022 would eliminate the need to use dotnet watch since hot reload is built into it.

**Comment by WayneHiller** [comment]
Having the same issue with a Blazor webassembly project with maybe 30 pages. 30 seconds to update. 15 seconds without hot reload.  Will try dotnet watch

**Comment by DamianEdwards** [comment]
If anybody is able to provide the source code to a project that exhibits this behavior it would be hugely helpful. We've been unable to reproduce this issue using any projects that we have access to or have attempted to synthetically generate.

**Comment by WayneHiller** [comment]
@DamianEdwards That could be difficult as the slow down is related to how big the project is and maybe how many dependencies within the same solution. Does anyone have a open source one that is slow during hot reload? I would be willing to share my project if it could be done in a way to keep it private as this is a real business app.

I tested dotnet watch on my Blazor Wasm project and it is many times faster. One of the pages was 30 seconds in VS and 9 seconds in watch. It is also very dependent on how many components are on the page being displayed. A sim[;e page goes to around 10-15 seconds in VS and 1 second in watch.

**Comment by DamianEdwards** [comment]
@WayneHiller yeah we've tried to generate examples of both (lots of pages, lots of components) but have yet to reproduce the kinds of times being reported, hence the request. If someone is able to isolate the behavior in a project that they can share it would really help move this forward.

**Comment by pranavkm** [comment]
Also, we'd be happy to receive these apps over our work addresses so it's not publicly shared. @PriyaPurkayastha in case you'd like to suggest alternatives here.

**Comment by PriyaPurkayastha** [comment]
Yes, we have a light-weight process to help onboard non-OSS customer apps into the .NET AppCompat lab. Please reach out to me on .NET External DL <dotnet@microsoft.com> and I can help with next steps.

**Comment by WayneHiller** [comment]
Is there any detailed logging we can turn on to see where hot reload is spending all the time?

**Comment by oiBio** [comment]
@DamianEdwards 
I could reproduce the issue with the sample project and copieing the counter.razor a few hundret times. 
As mentioned here https://developercommunity.visualstudio.com/t/Hot-Reload-in-VS-very-slow-but-fast-wit/1563649
The repo is here: https://github.com/oiBio/BlazorHotReloadIssue

**Comment by aarondcoleman** [comment]
I'm also having this issue. We have a large ASP.NET web app that's a mix of Serverside Blazor and ASP.NET MVC and it can take anywhere from 10-25 seconds to see a hot reload update. I've tried all browsers and checked for errors in the dev tools console. @DamianEdwards I can't ship you the app but I can be available during standard business hours to do a screen share / remote debug troubleshoot session against our dev environment if that's helpful.

**Comment by 0ptim** [comment]
I'm experiencing the same as other people described. In VS 2022 the changes take very long until applied. Using `dotnet watch run` from console improves performance by large.

Would love to use Hot Reload with VS 2022!

Congrats on the .net 6 release! 🎉

**Comment by InciteGmbH** [comment]
For us the same with a large project. **When will this be fixed**? Thanks.

**Comment by CommonLoon102** [comment]
Same issue like for the others (large Blazor-Server project). Thanks a lot for the `dotnet watch` trick! This way Hot Reload is usable.

**Comment by DamianEdwards** [comment]
Thanks folks, I think we have a repro now (@pranavkm correct me if I'm wrong). We'll update this thread with more details when we have them.

**Comment by lucianparvu** [comment]
@pranavkm I can't see improvements too , It seems to be same results like in RC1, RC2 in my project. 

In my case Visual Studio 2022 build the project in 14 seconds and Visual Studio 2019 in 10 Seconds .

Another Question : Hot Reload will work for Isolated CSS ? I have tested but is not working and needs build .

**Comment by CommonLoon102** [comment]
> Another Question : Hot Reload will work for Isolated CSS ? I have tested but is not working and needs build .

Static CSS (in wwwroot/css) updates as you type. Scoped CSS works on save or hot reload and updates instantly. Except on Windows 7, there it needs a rebuild.

**Comment by burtonrodman** [comment]
was hoping to replace Razor Runtime Compilation with Hot Reload (because of all the compile warnings about CodeAnalysis version mismatches).  i generally use vscode but couldn't get dotnet watch working there quickly.  The rest of my team uses Visual Studio, so thought maybe I would just switch.

after updating to VS 2022 17.0.2, Hot Reload works, but I'm seeing 25 - 60 seconds on a Surface Laptop 3 i7/16GB in a Razor Pages project with 279 .cshtml files.

if it would be helpful to submit my project, I can work with my client to get authorization.

**Comment by lucianparvu** [comment]
@pranavkm do we have any news on this ? When we should see improvements ?

**Comment by Mike-E-angelo** [comment]
Right now with 17.1.1 preview I am seeing a 40-60 second compile-time on my project for the simplest of changes.  This is before hot reload gets involved.  So, it would seem that the current Razor build system really struggles with larger projects in general. 😞

**Comment by lucianparvu** [comment]
> Right now with 17.1.1 preview I am seeing a 40-60 second compile-time on my project for the simplest of changes. This is before hot reload gets involved. So, it would seem that the current Razor build system really struggles with larger projects in general. 😞

In my case, i have hot reload after ~ 40 - 1.5 min seconds on every .razor file, everything else ( css, pure C# files ) takes ~1-2 seconds

**Comment by Contengo** [comment]
Same here - it's actually significantly quicker to stop, edit and run again than to use hot reload, which means we're back where we started. Sigh.

**Comment by pranavkm** [comment]
For the folks pinging about hot reload being slow in VS, we have a candidate fix available that we will be making available as part of 17.2-previews / 6.0.300 version of .NET SDK. I'll post on this thread again once the SDK changes are in and available as part of a Visual Studio preview release. 

@lucianparvu unfortunately we haven't quite gotten to the bottom of the slowness you experienced with dotnet-watch. If you do continue seeing it with VS, it'd great if you could file a VS feedback issue. Feedback issues capture additional diagnostics that should help us narrow down any issues in the source generator / razor compiler that contribute to the slowness.

**Comment by KonnectSalon** [comment]
Is there any workaround for this.
The Edit and Continue in vs2017 works 100% fine and then we release vs2022 with a 5 hour video telling us how Hot Reload (Edit and Continue) will save the day but it really just makes everything I do now less productive. I cannot even make a small HTML change in a cshtml file without waiting 5 minutes or having to stop and reload. And on that matter only being able to stop once VS2022 says that's OK cause it keeps popping up an error.

With respect, is there any workaround. I can't really wait until 17.2-previews that's just crazy.

**Comment by lucianparvu** [comment]
> @lucianparvu unfortunately we haven't quite gotten to the bottom of the slowness you experienced with dotnet-watch. If you do continue seeing it with VS, it'd great if you could file a VS feedback issue. Feedback issues capture additional diagnostics that should help us narrow down any issues in the source generator / razor compiler that contribute to the slowness.

I have submitted a VS Feedback with VS record: https://developercommunity2.visualstudio.com/t/Blazor-Net-Core-6-Slow-for-big-Projects/1645384?entry=problem&ref=native&refTime=1643014712342&refUserId=bc8b0145-3228-6f54-b025-ab2ae9ec254a

**Comment by Mike-E-angelo** [comment]
In my case, Hot Reload still does not work for my solution, using 17.1 Preview 3.  I will make an edit and after many many minutes have passed, no edits are observed.

Additionally, when attempting to exit debugging mode, I am met with this dialog:
https://developercommunity.visualstudio.com/t/Unable-to-Stop-Debugging-Code-0x80004005/1580495

Additionally, attempting to close the IDE directly results in the following message:

![](https://i.imgur.com/NhiXDWc.png)

Following the directions do not work and I am still met with the `0x80004005` exception above.

As I can no longer exit out of debug mode due to this exception dialog, I am now forced to close the IDE from Task Manager.

Not only does this feature still not seem to work, but it also appears to have gotten worse, as before I was able to exit debug mode after several seconds when encountering this exception.  Now, it is stuck and I have no choice but to use Task Manager to regain control of my environment.

Any consideration towards addressing this would be greatly appreciated.

**Comment by pranavkm** [comment]
@KonnectSalon I'm sorry you're having a bad experience with this. There's an option to [disable hot reload](https://developercommunity.visualstudio.com/t/How-to-disable-Hot-Reload-for-ASPNET-Co/1506697#T-N1560686) and keep using EnC until a fix is made available.

@Mike-E-angelo using the VS feedback tool would be the best way to go since your issue sounds specific to the VS debugger. 

While I appreciate your continued feedback, they would be much more actionable either as VS feedback issues if they are VS / debugger specific, or as separate issues for us to better track them. I'm going to close this issue for further discussion and post an update to it once a build of VS that resolves the slowness becomes available.

**Comment by danroth27** [comment]
Ongoing work to address this issue is tracked by https://github.com/dotnet/razor-compiler/issues/144
