### ISSUE TITLE
Reiteration on the SigninManager<T> not being supported in Razor Components

### ISSUE THREAD

**Issue by marwalsch** [dotnet/aspnetcore#34095]
I know this topic has been picked up several times already but there is still a lot of contradiction between alleged technical limitations and claims about stable work-arounds regarding the usage of the `SinginManager<T>` in pure Razor components.

First of all, I am not trying to reinvent the wheel, I am just trying to purify the Blazor Server project template and the Identity scaffolding from any `cshtml `to avoid a hybrid solutions; among other reasons this is because of the used UI library being built entirely on Razor components. 

What killed this entire venture off was a [comment ](https://github.com/dotnet/aspnetcore/issues/21199#issuecomment-620046268)made by @javiercn stating _"Identity uses cookies and cookies require an HTTP response to be set. That makes this impossible to use with Blazor by definition [...] This is not something Blazor can/will solve"_.  However, recent activites in this issue show that a[ similar issue to this](https://github.com/dotnet/aspnetcore/issues/13601) one is being set to `reevaluate`.

This really bothers me as I still cannot fathom how me cannot rely on the HTTP-Context on server side rendered pages, regardless of the underlying communication protocol. The accepted solution on this [stack-overflow thread](https://stackoverflow.com/questions/59538318/how-to-use-the-httpcontext-object-in-server-side-blazor-to-retrieve-information) elaborates just that:

 "_The fiction that the HttpContext object can't be used with Blazor Server App, has been long propagated on Stackoverflow, and it is high time to pension it off.
It is true that the HttpContext is not available when a WebSocket connection is in operation, but this must be clear: When you type an url and press the enter button, the connection to your server-side Blazor app is an HTTP connection, and not a WebSocket connection._"

With this in mind, I can just not see how we can't rely on the `HttpContext` here. The user has to build up a connection to the site, gets assigned a circuit id and can interact with the page, he has to run through (most) of the configured request pipeline; so there must be a HTTP connection, right? And if that is not reliable, how can we possibly expect any other service relying on any connection metadata to work? How can components using the `<AuthorizeView/>` with the underlying `AuthenticationStateProvider` (which itself relies on a `UserManager<T>`) enforce  authorization policies properly if we cannot even expect `SinginManager<T>` to work?

Are there any plans on removing the restriction of `SignInManager<T>` in Razor components or do we have to settle with tainting our Blazor projects with plain `cshtml` for good?

**Comment by javiercn** [comment]
@marwalsch thanks for contacting us.

All the information we've provided through multiple issues is still accurate. When a Blazor server application starts the Http connection is upgraded to a websocket and at that point there is no more HTTP connection and the HttpContext stops making sense, because the original request is long gone (upgraded to a websocket) and there is no way for the server to send an HTTP response since the connection has been upgraded to a websocket (is not longer an http connection). 

It is for that reason that SigninManager<T> does not work in Blazor Server applications, because even though the computation happens on the server, the page is rendered on the client and behaves like a SPA as opposed to a traditional server rendered app.

The reevaluate tag is there for us to follow up on the thread and take appropriate action, it doesn't mean we are necessarily going to reconsider doing something in this area.

In this case, it is by design that Identity is designed to work with Cookies for sign-in and that it is not compatible with the way Blazor Server works. If there were an easy way to make it work, we would have done so, but the reality is that there isn't.

There's no easy way to implement cookie authentication in Blazor Server without a redirect, and it's not our goal to support multiple Identity UI flavors based on developer choices/preferences. We believe that mix and match razor pages with Blazor is perfectly acceptable, we provide a default implementation for the UI based on Razor pages and that's what we recommend people using.

If you want to pursue an implementation free of Razor Pages, it's up to you to come up with a solution that works for your use cases. We don't plan to offer such solution out of the box nor recommend anyone doing so.

We understand that this is likely not the answer that you expect to hear, however this an area where we already have a solution we consider appropriate and we don't think we should investing in supporting an alternative implementation (if at all possible) with likely different security characteristics.

**Comment by ParadiseFallen** [comment]
Why not to use Interface for that and put logick for that there? When we loading first time there will be current impl. For next request it will change to WS impl (if ws connection performed). 

Also whats about blazor wasm auth?

**Comment by MarcoTheFirst** [comment]
I have already posted a solution to this problem a while back: https://github.com/dotnet/aspnetcore/issues/13601. Blazor Server and cookie auth work perfectly well together if you do a single fullpostback per user session. All it takes is a temporary credential cache, which I implemented in the form of a ConcurrentDictionary.

I have several solutions in production using this method, and it works like a charm. No need for cshtml. The only downside: I had to re-create all identity templates as razor components. But if you're just using the basics, that's not a big issue.

I'm surprised Microsoft doesn't want to pick up this solution as a standard since it integrates much more smoothly than using cshtml-stuff.

**Comment by javiercn** [comment]
> Why not to use Interface for that and put logick for that there? When we loading first time there will be current impl. For next request it will change to WS impl (if ws connection performed).

I'm not sure I understand what you are suggesting here, I also don't think it would work, but I'm happy to be proven wrong. All the methods in SignInManager are virtual, so nothing should block you from creating your own implementation.

> Also whats about blazor wasm auth?

Blazor webassembly uses a different authentication mechanism (OAuth) and also relies on Identity and razor pages.

**Comment by MarcoTheFirst** [comment]
PS: The principle I used in my solution is:

1. Redirect to /login razor component for all anonymous users
2. in your login-component, inject the SignInManager and use CheckPasswordSignInAsync() instead of PasswordSignInAsync(). This prevents Identity from trying to issue a cookie.
3. Once the login checks out, you cache username/pw in a dictionary using a GUID as key. 
4. You pass the guid back to your login-view, which then performs a pull postback to the same URL using the key as URL-param (e.g. /loing?key={guid-here} ). 
5. A custom http middleware class checks for the key param. If it encounters it, then it calls SignInManager.PasswordSignInAsync() and thereby creates the cookie at the right stage of the request lifecycle.
6. Now you just clear your cache for security reasons, and that's it.

**Comment by javiercn** [comment]
> I have already posted a solution to this problem a while back: #13601. Blazor Server and cookie auth work perfectly well together if you do a single fullpostback per user session. All it takes is a temporary credential cache, which I implemented in the form of a ConcurrentDictionary.
> 
> I have several solutions in production using this method, and it works like a charm. No need for cshtml. The only downside: I had to re-create all identity templates as razor components. But if you're just using the basics, that's not a big issue.
> 
> I'm surprised Microsoft doesn't want to pick up this solution as a standard since it integrates much more smoothly than using cshtml-stuff.

We already provide a solution that works and we think its appropriate and from what we can see, nothing is blocking anyone from creating a package and providing an alternative solution/implementation. We already offer a solution with well-known security characteristics and don't think we need to be creating and supporting alternative solutions for the same problem. Its up to the community to develop alternatives in this area and for other developers to evaluate them and decide whether or not they want to trust it. The solution we provide is the one we recommend everyone to use.

While your solution might work perfectly (and I'm not implying it does), its not something we would adopt without following the appropriate processes to guarantee the correctness and security characteristics of the solution, which takes time, resources and has a long term maintenance cost which we are not willing to accept.

**Comment by marwalsch** [comment]
@javiercn Thanks for the rapid response. If the current solution is the proposed one and will stay that way, that's your decision and I accept that.

But I am still not even close to comprehend why this issue is specifically and apparently only tied to the _SingInManager<T>_ (or is it not?).

_"even though the computation happens on the server, the page is rendered on the client and behaves like a SPA as opposed to a traditional server rendered app. [...] it is by design that Identity is designed to work with Cookies for sign-in and that it is not compatible with the way Blazor Server works"_
Even in a pure SPA I could make the server create a cookie and have the client include it in every request (which may be considered bad practice as it contradicts with statelessness but that's not the point here). 
If Blazor _Server_(!) is not even suitable for cookie authentication without essentially tampering with other framework technologies, what should I fallback to in the ideal case? Stateless authentication with bearer tokens as well?

Maybe you could explain what exact aspect of the HttpContext the` SignInManager<T>` works with/requires which is not worked with/required in other services which appear to be working in pure Razor components. Is it _setting_ the authentication token rather than just reading it? 
Again,  the entire `<AuthorizeView/>` depends on the `UserManager`. Why i **that** one supported? Authorization is entirely based on Claims, Roles and Identity which all depend on context.

**Comment by marwalsch** [comment]
Blazor Server and ASP.NET Core Identity are amazing solutions respectively but IMO the way they interoperate currently does not live up to that greatness.

**Comment by javiercn** [comment]
@marwalsch Identity (through SignInManager) requires setting up a cookie in the HttpResponse to establish the authentication context. It's not possible to do that once a Blazor Server application has started because the request has already been upgraded to a websocket. It's not something specific to Identity but to any component that needs to rely on the HttpContext.

Other parts of identity like UserManager work because they don't rely on the HTTP Cookie in their implementation.

Things like AuthorizeView work because we capture the authenticated user within SignalR Blazor and set it up when the app is starting, however, at that point the app has already upgraded the connection to a websocket and nothing that alters the response can be done.

**Comment by MarcoTheFirst** [comment]
@javiercn : I agree with @marwalsch and many others on this: Having CSHTML intermixed in a Blazor Server app for login purposes feels counterintuitive and contradicts the more elegant approach used in WASM flavor. While I do understand the technical difficulty of issuing a cookie in this scenario, I have demonstrated that it can be solved. Now obviously my solution isn't perfect yet, but that's only due to the fact that I can't go any lower than your SignInManager's API (and in fact I have made it much more sophisticated and secure in my production env). 

Of course the community (like myself) can find solutions and post them. But don't you find it a bitt odd that just for auth-purposes, blazor server has to resort back to an older technology which - on top of things - has a completely different look-and-feel than the razor templates? 

But anyway, I don't want to start an argument here :-) If anybody wants my help or inspiration, I'm more than willing.

**Comment by ParadiseFallen** [comment]
> I have already posted a solution to this problem 
can u send link with repo of this solution and samples for it?

**Comment by MarcoTheFirst** [comment]
@ParadiseFallen just check out my other github post. I had attached a zip file containing a sample. Unfortunately I haven't had time to create clean repo, but it's all in there: https://github.com/dotnet/aspnetcore/issues/13601#issuecomment-682768401

**Comment by marwalsch** [comment]
@javiercn So it is really just limited to _setting_ cookies? Antiforgery tokens and metadata cookies can still be _read_ from the context in Razor files after all. I had a similar occurrence with a culture cookie which apparently only works when set from within the `host.cshtml` file. I that's the case the lack of access to the HttpContext is extremely misleading, as it consists of more than just cookie data.
Aside form the low level abstraction through SignalR  the identity cookie and its configuration appear to applied properly.

**Comment by marwalsch** [comment]
@MarcoTheFirst If there's going to be an actual repo one day that the Identity Scaffolding in Razor I'd be glad to contribute and engage in discussion on it's security considerations
.

**Comment by MarcoTheFirst** [comment]
> @MarcoTheFirst If there's going to be an actual repo one day that sort of rewrites the Identity Scaffolding in Razor I'd be glad to contribute and engage in discussion on it's security considerations. That's essentially what I was looking for.

sure, I'll let you know if/when I find time to do so. In the meantime I advise you to take a look at my sample. It's hard for me to imagine any serious security concerns with this approach. All I essentially do is postpone the actual issuing of the cookie by a few milliseconds so that it can be issued in the context of a new http(s) request. After that everything continues 100% within the Identity framework standards. All other Identity methods have worked without full postback and therefore don't require additional tweaking.

**Comment by ParadiseFallen** [comment]
@javiercn why not to build some auth inside SignalR? Then when you register you can swap default sign in manager to SignalRSignInManager. Then app probably can change auth state on server. Also if cookiea required for client there can be IJsInterop for setting cookies

**Comment by MarcoTheFirst** [comment]
@ParadiseFallen I had a similar idea: Just call a separate ApiController endpoint using IJsInterop, then you get a full postback to set the cookie without disrupting the UI experience. I just haven't taken the time to try it since my workaround works very well for now.

**Comment by ParadiseFallen** [comment]
@javiercn  @MarcoTheFirst Or there can be just http request as normall to api as said @MarcoTheFirst. Then you will have ws + http. Perform request to /auth (sample). Blazor validate and sign in user. Then server uses ws to set cookies on client (rpc probably) and call refresh for user auth.

**Comment by ParadiseFallen** [comment]
@MarcoTheFirst I dont know how auth work fully. Tho probably ws connection cant change any creditionals when it opened once. Probably there way to reconect with new creditionals where you will be logging in.

**Comment by ParadiseFallen** [comment]
This issue not resolved

**Comment by marwalsch** [comment]
@javiercn I'd also request a re-open, as I am very sure this question will definitely continue to re-emerge if there is no further explanation at some point, ideally here. Could you confirm/falsify my last assumption? Or point me to other resources to research on this (other than the lacking docs of course)?
If it was truly just related to cookies, there should be huge overhaul on the docs as they are extremely misleading  in regards to this and probably the cause of the alleged rumours on the inconsistencies of the `HttpContext`. 
If the unavailability is in fact true, I am truly wondering how anyone gets a Blazor Server app running in production without a consistent context. For instance, the entire middleware API relies on the HttpContext through the `InvokeAsync(HttpContext context)` method. Does that mean we should expect the integrated and our own middleware to occasionally just  blunder entirely? 
If that's truly the case, I am afraid I have to re-think our entire tech-stack as this appears broken by design to me.

**Comment by marwalsch** [comment]
@MarcoTheFirst I just took a closer look at the idea of your [workaround ](https://github.com/dotnet/aspnetcore/issues/13601)and I believe it essentially proves that the restrictions are really just about the cookie response writing behaviour of certain methods of the `SignInManager`. 
After all, you still end up using a middleware (which is executed entirely through the SignalR connection lifetime if I am not mistaken) and still relies on context (i.e. reading cookies and such is no issue, as to what my point about the `<AuthorizeView/> ` was.
The conclusion made in the docs to simply state 
![image](https://user-images.githubusercontent.com/72074423/125630691-670aed4b-a6a5-4473-95e0-895c64fc059c.png)
is, in terms of comprehension, a kick to the groin for any developer getting into the top like myself (fairly spoken, this is primarily an issue with the docs).

PS: Speaking of security considerations in the proposed workaround, I am far from being an expert on the topic when it gets into this level of detail; but i think the temporary in-memory storage of signed in users and passwords in the middleware might expose a risk when it comes to session hijacking. Just dumping first thoughts here though.
