### ISSUE TITLE
System.IO.Pipelines.PipeReader.CopyToAsyncCore: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')

### ISSUE THREAD

**Issue by usaguerrilla** [dotnet/aspnetcore#38771]
### Description

Getting this exception in ASP.NET Core Runtime 5.0.11
Occurs occasionaly (quite small %).
I checked and request seems to be not in cancelled state after it throws.

```
context?.HttpContext?.RequestAborted.IsCancellationRequested == false
```

Exception:

```
An unhandled exception was thrown by the application. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at MP.Sdk.Edge.Web.Formatters.InputFormatterBase.ToBytesAsync(Stream stream) in /opt/teamcity/work/af8a0ab010c87174/src/Sdk/MP.Sdk.Edge.Web/Formatters/InputFormatterBase.cs:line 65
```

```
using (MemoryStream memoryStream = new MemoryStream())
{
    using (stream)
    {
        // below throws
        await stream.CopyToAsync(memoryStream);
    }

    return memoryStream.ToArray();
}
```

### Reproduction Steps

Reproes in AWS with load balancer. No luck reproducing locally so far.

### Expected behavior

shouldn't throw exception

### Actual behavior

Exception:

```
An unhandled exception was thrown by the application. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at MP.Sdk.Edge.Web.Formatters.InputFormatterBase.ToBytesAsync(Stream stream) in /opt/teamcity/work/af8a0ab010c87174/src/Sdk/MP.Sdk.Edge.Web/Formatters/InputFormatterBase.cs:line 65
```

### Regression?

was okay in netcoreapp2.1

### Known Workarounds

none so far

**Comment by usaguerrilla** [comment]
here is wireshark capture:

[capture.zip](https://github.com/dotnet/aspnetcore/files/7636879/capture.zip)

**Comment by halter73** [comment]
Thanks for the quick network traces! I see there's a mismatch between the Content-Type request header and the actual content type, but that by itself does not explain how this error could occur.

Do you know if something tried to read the request body as a form before `SdkWebContextInputFormatter` called `stream.CopyToAsync(memoryStream)`? Nothing at the `HttpRequestStream`/`HttpRequestPipeReader` layer references the request's Content-Type since they just deal with raw bytes and don't decode the content, but it's possible that ASP.NET's form reading logic left the request body in a bad state. We fixed a bug like this early in .NET 6 with https://github.com/dotnet/aspnetcore/pull/27586. We didn't backport it because there weren't too many reports, and it effectively just changes the error message. That said, backporting could save people from wasting time investigating this kind of issue in the future. @Tratcher 

@usaguerrilla Can you upgrade your app to .NET 6 and see if that changes the error?

**Comment by usaguerrilla** [comment]
trying to create simple repro, but porting to .net6.0 didn't fix the issue

**Comment by usaguerrilla** [comment]
!!!README.TXT!!!

```
start using:

dotnet run

make sure to replace ip variable in curl-test.bat and curl-test-repro.bat

curl-test.bat <- call with payload which works
curl-test-repro.bat <- call with payload which doesn't work
```

[ReproApp.zip](https://github.com/dotnet/aspnetcore/files/7637995/ReproApp.zip)

**Comment by adityamandaleeka** [comment]
@sebastienros Can you please take a look at the repro?

**Comment by sebastienros** [comment]
I have a simpler repro app that only involves an `InputFormatter` that tries to read the body when the content-type is `application/x-www-form-urlencoded`.
Other tests seem to show that the body was already read that point, while it can still be read completely when using a different content-type.

**Comment by sebastienros** [comment]
Reason seems to be that `application/x-www-form-urlencoded` triggers `IFormFeature` to already parse the collection.

**Comment by sebastienros** [comment]
Found a mitigation. The feature has an option to buffer the body which makes it possible to read it again. So applying `[RequestFormLimits(BufferBody = true)]` on the action or configuring `FormOptions.BufferBody` will make the current sample work.

**Comment by sebastienros** [comment]
@Tratcher helped me repro the issue without MVC which means it's very probably a bug in Kestrel. I am working on a fix.
