### ISSUE TITLE
Hub SignalR freezing main thread called from another thread

### ISSUE THREAD

**Issue by Viamo** [dotnet/aspnetcore#44578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SignalR has cross threading bug which is detailed [here](https://stackoverflow.com/questions/73100026/hub-signalr-freezing-main-thread-called-from-another-thread).

### Expected Behavior

Should not use the main thread and should not freeze.

### .NET Version

5.0

**Comment by davidfowl** [comment]
Can you provide a full repro with code that we can run? That would help narrow down what the issue might be. There isn't enough issue in that stackoverflow post to understand what's happening.

**Comment by BrennanConroy** [comment]
Also, try using the 7.0 client, we updated the code to use `ConfigureAwait(false)` to improve the experience in UI apps.

**Comment by Viamo** [comment]
@davidfowl Here is [SignalRTest](https://github.com/Viamo/SignalRTest) WPF project.
@BrennanConroy What do you mean? The latest version in NuGet is [6.0.10](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client).
How to use ConfigureAwait(false) from new HubConnectionBuilder()*?

**Comment by BrennanConroy** [comment]
https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/7.0.0-rc.2.22476.2

**Comment by Viamo** [comment]
@BrennanConroy Thank you! Updated to version 7.0.0.
But it still hangs (the same sources). How to use ConfigureAwait(false)?

**Comment by BrennanConroy** [comment]
```csharp
await new HubConnectionBuilder().WithUrl($"https://localhost:5001/").Build().StartAsync().ConfigureAwait(false);
```

**Comment by Viamo** [comment]
Tested with .ConfigureAwait(false); - it still hangs.

**Comment by Viamo** [comment]
I installed this files:
> dotnet-runtime-7.0.0-rc.2.22472.3-win-x64.exe
> dotnet-runtime-7.0.0-rc.2.22472.3-win-x86.exe
> dotnet-sdk-7.0.100-rc.2.22477.23-win-x64.exe
> dotnet-sdk-7.0.100-rc.2.22477.23-win-x86.exe
> windowsdesktop-runtime-7.0.0-rc.2.22472.13-win-x64.exe
> windowsdesktop-runtime-7.0.0-rc.2.22472.13-win-x86.exe

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.6

But still cannot select target framework .NET 7.0 (I guess this is off topic)

**So I'll ask why SignalR with `.ConfigureAwait(false);` still hangs in .NET6 and can I somehow make it work properly in .NET6?**

**Comment by BrennanConroy** [comment]
Since the app you provided does not reproduce the issue can you please provide a dump of the process when it freezes.

Also, when you say freezes, you mean it hangs until you close the application?

**Comment by Viamo** [comment]
I just noticed that it freezes/hangs only when debugging.
If I remove line 38, then nothing freezes/hangs.
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.6
[https://youtu.be/3i8Bgyckyfg](https://youtu.be/3i8Bgyckyfg)

**Comment by BrennanConroy** [comment]
Ok, so it freezes, not a hang. This is because at around 70 ticks the connection fails and exceptions are being thrown, because you're in VS it's triggering diagnostic events which slow down the process. If you a) have a faster computer this freeze is a lot less noticeable, b) are outside of VS these diagnostic events don't occur.

**Comment by Viamo** [comment]
At the end of the video you can see it hangs.
Could I avoid triggering diagnostic events in VS?
I'm using try catch. Why doesn't it help?
Why does not the same behavior happen on other exeptions? It happens only with SignalR.

**Comment by BrennanConroy** [comment]
> Could I avoid triggering diagnostic events in VS?

Not sure, maybe turn off the diagnostic tools, Tools -> Options -> Debugging -> General -> Enable Diagnostic Tools while debugging.

If the problem doesn't occur outside of debugging in VS then this isn't really an issue.

**Comment by Viamo** [comment]
ok, thanks
