### ISSUE TITLE
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by Seanxwy** [dotnet/aspnetcore#50529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When html code contains svg code, it doesn't work properly. When the svg code is removed, normal operation can be resumed.

`InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(byte[] buffer, int offset, int count)`

### Steps To Reproduce

In the template project, the exception can be reproduced by adding multiple svg codes

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="none" version="1.1" width="122" height="45" viewBox="0 0 152.06024169921875 46.666656494140625"><defs><filter id="master_svg0_15_171" filterUnits="objectBoundingBox" color-interpolation-filters="sRGB" x="-20" y="-16" width="165" height="80"><feFlood flood-opacity="0" result="BackgroundImageFix" /><feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" /><feOffset dy="4" dx="0" /><feGaussianBlur stdDeviation="5" /><feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.9690265655517578 0 0 0 0 0.9690265655517578 0 0 0 0.3019607961177826 0" /><feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow" /><feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape" /></filter></defs><g><g filter="url(#master_svg0_15_171)"><path d="M20.3238965625,11.91665275390625L20.2301465625,26.60417275390625Q20.1988965625,29.51037275390625,21.6259765625,31.20837275390625Q23.0530265625,32.90627275390625,25.7405265625,32.90627275390625Q28.4280265625,32.90627275390625,29.9072265625,31.26037275390625Q31.3968265625,29.61457275390625,31.3655265625,26.60417275390625L31.2405265625,12.55207275390625L36.0739265625,11.91665275390625L35.980126562500004,26.66667275390625Q35.9489265625,31.62497275390625,33.271826562499996,34.33337275390625Q30.6051265625,37.03127275390625,25.7405265625,37.03127275390625Q20.9072265625,37.03127275390625,18.2197265625,34.37497275390625Q15.5322265625,31.71877275390625,15.5322265625,26.66667275390625L15.5009765625,12.55207275390625L20.3238965625,11.91665275390625ZM40.2197265625,36.48957275390625L39.584326562499996,32.99997275390625L53.4072265625,16.041672753906248L41.4697265625,16.90627275390625L40.1884265625,12.78124275390625L59.1364265625,11.91665275390625L59.7718265625,15.30207275390625L46.0426265625,32.302072753906245L58.9697265625,31.36457275390625L59.9384265625,35.56247275390625L40.2197265625,36.48957275390625ZM74.5634265625,37.16667275390625Q71.7197265625,37.16667275390625,69.5843265625,36.30207275390625Q67.4593265625,35.43747275390625,65.99052656250001,33.802072753906245Q64.5218265625,32.166672753906255,63.6989265625,29.83337275390625Q62.8864265625,27.49997275390625,62.6989265625,24.55207275390625Q62.5322265625,21.80207275390625,63.2718265625,19.416672753906248Q64.01142656249999,17.03127275390625,65.49052656250001,15.27087275390625Q66.9801265625,13.51040275390625,69.1260265625,12.51040275390625Q71.2718265625,11.49999275390625,73.9593265625,11.49999275390625Q76.7093265625,11.49999275390625,78.8239265625,12.36457275390625Q80.9384265625,13.22915275390625,82.3864265625,14.87497275390625Q83.8447265625,16.52087275390625,84.6468265625,18.90627275390625Q85.4489265625,21.29167275390625,85.5426265625,24.33337275390625Q85.6364265625,27.33337275390625,84.8655265625,29.71877275390625Q84.1051265625,32.104172753906255,82.6260265625,33.76037275390625Q81.1572265625,35.40627275390625,79.0947265625,36.29167275390625Q77.0322265625,37.16667275390625,74.5634265625,37.16667275390625ZM75.24052656250001,33.614572753906245Q76.8447265625,33.51037275390625,77.9905265625,32.64587275390625Q79.1468265625,31.78127275390625,79.8447265625,30.37497275390625Q80.5530265625,28.96877275390625,80.7718265625,27.13537275390625Q81.0010265625,25.29167275390625,80.7718265625,23.20837275390625Q80.5530265625,21.26037275390625,79.8968265625,19.70837275390625Q79.2405265625,18.15627275390625,78.2093265625,17.08337275390625Q77.1884265625,16.01037275390625,75.8134265625,15.49997275390625Q74.4384265625,14.98957275390625,72.80302656250001,15.11457275390625Q71.1468265625,15.23957275390625,70.01142656249999,16.104172753906248Q68.8760265625,16.96877275390625,68.19892656249999,18.33337275390625Q67.5322265625,19.68747275390625,67.3343265625,21.43747275390625Q67.1468265625,23.17707275390625,67.3343265625,25.06247275390625Q67.5322265625,26.82287275390625,68.11552656250001,28.40627275390625Q68.7093265625,29.98957275390625,69.6884265625,31.19787275390625Q70.6676265625,32.39587275390625,72.05302656250001,33.052072753906245Q73.44892656249999,33.70837275390625,75.24052656250001,33.614572753906245ZM94.4593265625,11.91665275390625L106.2301265625,29.12497275390625L106.2926265625,29.12497275390625L106.1051265625,12.55207275390625L110.9697265625,11.91665275390625L110.7405265625,36.48957275390625L106.3551265625,36.81247275390625L94.2926265625,19.94787275390625L94.2301265625,19.916672753906248L94.1051265625,36.48957275390625L89.7510265625,36.81247275390625L89.5322265625,12.55207275390625L94.4593265625,11.91665275390625ZM119.5532265625,11.71874275390625L125.1882265625,20.104172753906248L130.85522656249998,11.71874275390625L135.6152265625,12.90624275390625L127.9072265625,24.01037275390625L136.23022656249998,35.114572753906245L131.10522656249998,36.64587275390625L125.1882265625,27.94787275390625L119.3032265625,36.64587275390625L114.5012265625,35.114572753906245L122.5012265625,24.01037275390625L114.8552265625,12.90624275390625L119.5532265625,11.71874275390625Z" fill="#0AAD0A" fill-opacity="1" /><path d="M20.3238965625,11.91665275390625L20.2301465625,26.60417275390625Q20.1988965625,29.51037275390625,21.6259765625,31.20837275390625Q23.0530265625,32.90627275390625,25.7405265625,32.90627275390625Q28.4280265625,32.90627275390625,29.9072265625,31.26037275390625Q31.3968265625,29.61457275390625,31.3655265625,26.60417275390625L31.2405265625,12.55207275390625L36.0739265625,11.91665275390625L35.980126562500004,26.66667275390625Q35.9489265625,31.62497275390625,33.271826562499996,34.33337275390625Q30.6051265625,37.03127275390625,25.7405265625,37.03127275390625Q20.9072265625,37.03127275390625,18.2197265625,34.37497275390625Q15.5322265625,31.71877275390625,15.5322265625,26.66667275390625L15.5009765625,12.55207275390625L20.3238965625,11.91665275390625ZM40.2197265625,36.48957275390625L39.584326562499996,32.99997275390625L53.4072265625,16.041672753906248L41.4697265625,16.90627275390625L40.1884265625,12.78124275390625L59.1364265625,11.91665275390625L59.7718265625,15.30207275390625L46.0426265625,32.302072753906245L58.9697265625,31.36457275390625L59.9384265625,35.56247275390625L40.2197265625,36.48957275390625ZM74.5634265625,37.16667275390625Q71.7197265625,37.16667275390625,69.5843265625,36.30207275390625Q67.4593265625,35.43747275390625,65.99052656250001,33.802072753906245Q64.5218265625,32.166672753906255,63.6989265625,29.83337275390625Q62.8864265625,27.49997275390625,62.6989265625,24.55207275390625Q62.5322265625,21.80207275390625,63.2718265625,19.416672753906248Q64.01142656249999,17.03127275390625,65.49052656250001,15.27087275390625Q66.9801265625,13.51040275390625,69.1260265625,12.51040275390625Q71.2718265625,11.49999275390625,73.9593265625,11.49999275390625Q76.7093265625,11.49999275390625,78.8239265625,12.36457275390625Q80.9384265625,13.22915275390625,82.3864265625,14.87497275390625Q83.8447265625,16.52087275390625,84.6468265625,18.90627275390625Q85.4489265625,21.29167275390625,85.5426265625,24.33337275390625Q85.6364265625,27.33337275390625,84.8655265625,29.71877275390625Q84.1051265625,32.104172753906255,82.6260265625,33.76037275390625Q81.1572265625,35.40627275390625,79.0947265625,36.29167275390625Q77.0322265625,37.16667275390625,74.5634265625,37.16667275390625ZM75.24052656250001,33.614572753906245Q76.8447265625,33.51037275390625,77.9905265625,32.64587275390625Q79.1468265625,31.78127275390625,79.8447265625,30.37497275390625Q80.5530265625,28.96877275390625,80.7718265625,27.13537275390625Q81.0010265625,25.29167275390625,80.7718265625,23.20837275390625Q80.5530265625,21.26037275390625,79.8968265625,19.70837275390625Q79.2405265625,18.15627275390625,78.2093265625,17.08337275390625Q77.1884265625,16.01037275390625,75.8134265625,15.49997275390625Q74.4384265625,14.98957275390625,72.80302656250001,15.11457275390625Q71.1468265625,15.23957275390625,70.01142656249999,16.104172753906248Q68.8760265625,16.96877275390625,68.19892656249999,18.33337275390625Q67.5322265625,19.68747275390625,67.3343265625,21.43747275390625Q67.1468265625,23.17707275390625,67.3343265625,25.06247275390625Q67.5322265625,26.82287275390625,68.11552656250001,28.40627275390625Q68.7093265625,29.98957275390625,69.6884265625,31.19787275390625Q70.6676265625,32.39587275390625,72.05302656250001,33.052072753906245Q73.44892656249999,33.70837275390625,75.24052656250001,33.614572753906245ZM94.4593265625,11.91665275390625L106.2301265625,29.12497275390625L106.2926265625,29.12497275390625L106.1051265625,12.55207275390625L110.9697265625,11.91665275390625L110.7405265625,36.48957275390625L106.3551265625,36.81247275390625L94.2926265625,19.94787275390625L94.2301265625,19.916672753906248L94.1051265625,36.48957275390625L89.7510265625,36.81247275390625L89.5322265625,12.55207275390625L94.4593265625,11.91665275390625ZM119.5532265625,11.71874275390625L125.1882265625,20.104172753906248L130.85522656249998,11.71874275390625L135.6152265625,12.90624275390625L127.9072265625,24.01037275390625L136.23022656249998,35.114572753906245L131.10522656249998,36.64587275390625L125.1882265625,27.94787275390625L119.3032265625,36.64587275390625L114.5012265625,35.114572753906245L122.5012265625,24.01037275390625L114.8552265625,12.90624275390625L119.5532265625,11.71874275390625Z" fill-opacity="0" stroke-opacity="1" stroke="#0AAD0A" fill="none" stroke-width="1" /></g></g></svg>`

### .NET Version

.net 8 p7

**Comment by Seanxwy** [comment]
Sample repository

https://github.com/Seanxwy/BlazorApp1

@davidfowl

**Comment by captainsafia** [comment]
@Seanxwy It looks like you might be running into a dupe of https://github.com/dotnet/aspnetcore/issues/49172. Can you try the latest RC1 nightlies available at github.com/dotnet/installer and see if that works for you?

**Comment by AhmedHemdan21** [comment]
I've encountered a potential issue with the .NET 8 Preview 7 Blazor Web App. Specifically, there appears to be a discrepancy in content rendering when a page has a significant amount of content (text/html). For context, I've noted that the exact same HTML logic works seamlessly on .NET 7 without any such issues.

Allowing AllowSynchronousIO from program.cs would prevent that issue but still, it will skip the rest of the content above the limitation and will now show limited content 

Steps to Reproduce:

1- Create .NET 8 Preview Web App

2- Go to Index.razor page 

3- Add the following snippet 

`
@{
    // even 25 times won't work
    for (int i = 0; i < 50; i++)
    {
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    }
}
`

**Comment by albertwoo** [comment]
I faced the same issue too with dotnet 8 preview 7.

**Comment by captainsafia** [comment]
@albertwoo @AhmedHemdan21 This issue was resolved in RC1 which was released today.

**Comment by AhmedHemdan21** [comment]
Thanks, @captainsafia, Confirmed it works now without issues

**Comment by albertwoo** [comment]
@captainsafia the issue exist if I use RazorComponentResult.

```csharp
app.MapGet("/demo", () => new RazorComponentResult<Demo>());
```

```razor
@{
    // even 25 times won't work \
    for (int i = 0; i < 50; i++)
    {
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.
        </p>
    }
}
```

**Comment by albertwoo** [comment]
Also if I use **ctx.RequestServices.GetService<Microsoft.AspNetCore.Components.Endpoints.IComponentPrerenderer>()** to render component, the issue remains.

**Comment by captainsafia** [comment]
> @captainsafia the issue exist if I use RazorComponentResult.
> 
> 
> 
> ```csharp
> 
> app.MapGet("/demo", () => new RazorComponentResult<Demo>());
> 
> ```
> 
> 
> 
> ```razor
> 
> @{
> 
>     // even 25 times won't work \
> 
>     for (int i = 0; i < 50; i++)
> 
>     {
> 
>         <p>
> 
>             Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
> 
>             has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
> 
>             scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
> 
>             electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
> 
>             Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
> 
>             PageMaker including versions of Lorem Ipsum.
> 
>         </p>
> 
>     }
> 
> }
> 
> ```

Mind filing a new issue for this with a repro?

**Comment by albertwoo** [comment]
As this issue is not fixec, I will keep comment on this one.

And here is the repo for reproduce: https://github.com/albertwoo/Blazor8Issue_LargeContent

**Comment by ouhndelof** [comment]
@captainsafia @albertwoo I have encountered the same problem when using `RazorComponentResult` and have created a new issue: #51174

I linked to your repo for reproduction.
