### ISSUE TITLE
MapBlazorHub configuration in NET8 throws a `The request matched multiple endpoints` exception

### ISSUE THREAD

**Issue by shrayasr** [dotnet/aspnetcore#51698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are working on migrating our blazor server application from NET6 to NET8 (to solve some auth issues we were having) and the guide advised this of us: 

```diff
- app.MapBlazorHub();
+ app.MapRazorComponents<App>()
+   .AddInteractiveServerRenderMode()
```

And we didn't know where to move the endpoint configuration to, which was previously being done in `MapBlazorHub`. Our previous call looked like this: 

```csharp
endpoints.MapBlazorHub(config =>
{
    config.CloseOnAuthenticationExpiration = true;
});
```

This was clarified by @guardrex in https://github.com/dotnet/AspNetCore.Docs/issues/30843 where it was asked for us to place the `MapBlazorHub` call after the call to `MapRazorComponents ... AddInteractiveServerRenderMode` block. Which we did.

However, after doing this, we got the following exception: 

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: Blazor initializers
```

And blazor doesn't seem to boot up on the browser.

### Expected Behavior

Expectation is as follows: 

- Project is upgraded to NET8 
- Server closes the connection when authentication expires as in NET6

### Steps To Reproduce

https://github.com/kalai-logicsoft/BlazorNet8AuthTest

## Console

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5191/_blazor/initializers - - -
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/_blazor/initializers'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'Blazor initializers' with route pattern '/_blazor/initializers/' is valid for the request path '/_blazor/initializers'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint '(null)' with route pattern '/_blazor/initializers/' is valid for the request path '/_blazor/initializers'
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
      Connection id "0HMUMNLG9R88S" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5191/_vs/browserLink - 200 - text/javascript;+charset=UTF-8 111.2111ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

      Blazor initializers

         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
      Connection id "0HMUMNLG9R88R" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5191/_blazor/initializers - 500 - text/plain;+charset=utf-8 53.8392ms
```

## Browser

```
GET http://localhost:5191/_blazor/initializers 500 (Internal Server Error)
(anonymous) @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
startCircutIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout (async)
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Ds @ blazor.web.js:1
```

```
VM69:1  Uncaught (in promise) SyntaxError: Unexpected token 'M', "Microsoft."... is not valid JSON
await (async)
startCircutIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout (async)
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Ds @ blazor.web.js:1
```

```
aspnetcore-browser-refresh.js:260  WebSocket connection to 'wss://localhost:44332/BlazorNet8AuthTest/' failed: 
(anonymous) @ aspnetcore-browser-refresh.js:260
getWebSocket @ aspnetcore-browser-refresh.js:257
(anonymous) @ aspnetcore-browser-refresh.js:16
aspnetcore-browser-refresh.js:19 WebSocket failed to connect.
```

### .NET Version

8.0.100-rc.2.23502.2

## `dotnet --info`

```
.NET SDK:
Version:   8.0.100-rc.2.23502.2
Commit:    0abacfc2b6

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.319 [C:\Program Files\dotnet\sdk]
  7.0.310 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by guardrex** [comment]
Thanks @shrayasr!

I'm 👂 for PU guidance on Blazor hub options for BWA apps. Our 8.0 section is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#blazor-hub-options

**Comment by guardrex** [comment]
@mkArtakMSFT ... A new docs issue arrived related to hub config. I was able to address part of the problem raised.

On https://github.com/dotnet/AspNetCore.Docs/issues/31113, the primary ask is about the 8.0-era replacement for `app.MapBlazorHub().RequireAuthorization(...)`, which I believe is `app.MapRazorComponents<App>().RequireAuthorization(...)`. I'm making that update now on https://github.com/dotnet/AspNetCore.Docs/pull/31114.

Earlier, I addressed the server-side circuit handler options. I think the guidance at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#server-side-circuit-handler-options

... is good 👍 (but a PU review of it is welcome).

However, the ask is also about the Blazor hub config guidance at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#blazor-hub-options

... which I think remains a problem. This is the second report that either it isn't configuring the Blazor hub.

I'll remain 👂 here for how to address it. I may as well add the remaining questions on hub config here so that we can address this in other articles as well ...

* *Related to* ☝️: In [app base path guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#server-side-blazor), what's the replacement for `app.MapBlazorHub("base/path");` for the Blazor hub?

* In the [interactive SSR security guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/interactive-server-side-rendering?view=aspnetcore-8.0#cross-origin-protection), there's a remark that probably should include demo code ...

  > CORS can be disabled for the Blazor SignalR hub by adding the \<xref:Microsoft.AspNetCore.Cors.DisableCorsAttribute> metadata to the endpoint metadata after calling \<xref:Microsoft.AspNetCore.Builder.ComponentEndpointRouteBuilderExtensions.MapBlazorHub%2A> on the endpoint route builder.

**Comment by kalai-logicsoft** [comment]
Thanks for the update @guardrex, We look forward to more guidance on this.

**Comment by ElliottBrand** [comment]
While not exactly the same use-case, #52156 is also related to MapBlazorHub and throws the Ambiguous Route Error when an app needs to have more than one, so I figured I'd mention it here as well. This worked fine in .Net 7.

**Comment by kcsahoo123** [comment]
Has there been any update on this?
I am still getting the error
 An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

Blazor initializers
when I am putting this code in program.cs in .net8 blazor interactive server app:
 app.MapRazorComponents<App>()
     .AddInteractiveServerRenderMode();
 app.MapBlazorHub(options =>
 {
     options.CloseOnAuthenticationExpiration = true;
 });
 app.MapRazorPages();

**Comment by kalai-logicsoft** [comment]
HI @kcsahoo123,

Still, we are facing this issue.

**Comment by FM1973** [comment]
Same here.
We are not able to set CloseOnAuthenticationExpiration in a .net 8 blazor web app.

**Comment by ecs87** [comment]
Same here as well.

MapBlazorHub() which resides in the dll C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.1\Microsoft.AspNetCore.Components.Server.dll are mapping endpoints that the following function (in Program.cs) has already mapped: app.MapRazorComponents<App>().AddInteractiveServerRenderMode();

Therefore, we can't have app.MapRazorComponents<App>().AddInteractiveServerRenderMode() and endpoints.MapBlazorHub(option => { option.CloseOnAuthenticationExpiration = true; }); in Program.cs at the same time or else it throws a AmbiguousMatchException.

IE: In :\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.1\Microsoft.AspNetCore.Components.Server.dll on lines 81 - 89:

`var disconnectEndpoint = endpoints.Map(
    (path.EndsWith('/') ? path : path + "/") + "disconnect/",
    endpoints.CreateApplicationBuilder().UseMiddleware<CircuitDisconnectMiddleware>().Build())
    .WithDisplayName("Blazor disconnect");

var jsInitializersEndpoint = endpoints.Map(
    (path.EndsWith('/') ? path : path + "/") + "initializers/",
    endpoints.CreateApplicationBuilder().UseMiddleware<CircuitJavaScriptInitializationMiddleware>().Build())
    .WithDisplayName("Blazor initializers");`

**Comment by halter73** [comment]
> And we didn't know where to move the endpoint configuration to, which was previously being done in `MapBlazorHub`. Our previous call looked like this:

This issue is not being tracked by #54080. Unfortunately, configuring the hub used by `AddInteractiveServerRenderMode` with `MapBlazorHub` will not work. For .NET 8, you'll be forced to either:

- Stick to not using `app.MapRazorComponents<App>()` like you did in .NET 7.
- Give your custom-configured Blazor Hub higher precedence using the new [WithOrder(int) method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.routingendpointconventionbuilderextensions.withorder?view=aspnetcore-8.0#microsoft-aspnetcore-builder-routingendpointconventionbuilderextensions-withorder-1(-0-system-int32)). I verified the following fixes the `AmbiguousMatchException` in https://github.com/kalai-logicsoft/BlazorNet8AuthTest
  ```csharp
  app.MapBlazorHub(config =>
  {
      config.CloseOnAuthenticationExpiration = true;
  }).WithOrder(-1);
  ```
- Or live without configuring custom hub options until a proper API is added in .NET 9.

**Comment by ecs87** [comment]
Thank you, Stephen! It made me realize...I'm an idiot and our auth issues with InteractiveServer were more related to that rendering mode than the MapBlazorHub method because MapBlazorHub in Program.cs (combined with app.MapRazorComponents<App>().AddInteractiveServerRenderMode()) and utilizing <script src="_framework/blazor.server.js" ></script> then setting the nodes in App.razor to @rendermode="InteractiveServer" made blazor.server.js error 500 in the browser console and threw everything into Static Server Side rendering mode (which works with auth when changing routes).

The only reason I was using MapBlazorHub in my Program.cs was to fix InteractiveServer mode not checking auth on route changes. Perhaps this warrants a different issue or more research.

**Comment by kswami74** [comment]
Hi, you can also try mapping the Blazor hub to a different path: `app.MapBlazorHub("/app")`

**Comment by jvelezc** [comment]
No idea why this worked
  app.MapBlazorHub("APP");
  But if you add random string in there the error goes away.

**Comment by kalai-logicsoft** [comment]
> No idea why this worked app.MapBlazorHub("APP"); But if you add random string in there the error goes away.

This will work because you are mapping the hub to a different endpoint, the change will throw the Blazor hub away / out of razor components, and the required `config.CloseOnAuthenticationExpiration = true;` will not work including any of the configuration which can be set from the `MapBlazorHub`.

Actually, it is not solving the problem, it is throwing the problem with the required options away..

**Comment by javiercn** [comment]
MapBlazorHub should not be called, as that will duplicate the endpoint (hence the ambiguity).

The following snippet should do the trick. @guardrex can you make sure that we cover this in docs?
```
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .Add(e =>
    {
        var metadata = e.Metadata;
        var dispatcherOptions = metadata.OfType<HttpConnectionDispatcherOptions>().FirstOrDefault();
        if (dispatcherOptions != null)
        {
            dispatcherOptions.CloseOnAuthenticationExpiration = true;
        }
    });
```

I filed https://github.com/dotnet/aspnetcore/issues/63520 to track making this scenario easier.

**Comment by javiercn** [comment]
@guardrex let's use the docs issue to track the remaining work in this area.

Making this easier in 11.0 is covered by https://github.com/dotnet/aspnetcore/issues/63520
