### ISSUE TITLE
Codespaces doesn't initialize correctly

### ISSUE THREAD

**Issue by PureKrome** [dotnet/aspnetcore#55272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

👋🏻 G'Day! I'm trying to start a new Codespace (ref: [contributing docs for codespaces](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#codespaces-on-github)) and it's not working -> it's erroring with:

![image](https://github.com/dotnet/aspnetcore/assets/899878/09285e42-7417-483e-9038-ce6cd381a9da)

I'm under the impression that starting a new codespace "should just work" and off we go!

### Expected Behavior

A codespace has been initialized with all the required dependencies and we can start running `dotnet build` and/or `dotnet test` in the terminal.

No errors should occur.

### Steps To Reproduce

- goto https://github.com/dotnet/aspnetcore
- ![image](https://github.com/dotnet/aspnetcore/assets/899878/845a0768-6903-4aa3-b141-c4f5c120c98d)
- click => `Create Codespace on main`
- Grab a 🍸😋 
- and .. error screen 😭 

### Exceptions (if any)

-na-

### .NET Version

-na-

**Comment by captainsafia** [comment]
@PureKrome Would you be able to share the creation logs from the crashed instance? You can find instructions on how to find them [here](https://docs.github.com/en/codespaces/troubleshooting/github-codespaces-logs).

**Comment by PureKrome** [comment]
Hi @captainsafia - absolutely! Sorry for not including this, earlier.

Here's the logs:

(and yes, it's showing garbage inthe log viewer)

```
2024-04-23 00:22:19.665Z: Host information
2024-04-23 00:22:19.684Z: ----------------
2024-04-23 00:22:19.685Z: OS: Ubuntu 22.04.3 LTS (stable release)
2024-04-23 00:22:19.685Z: Image details: https://github.com/github/codespaces-host-images/blob/main/README.md
2024-04-23 00:22:19.685Z: ----------------

=================================================================================
2024-04-23 00:22:19.685Z: Configuration starting...
2024-04-23 00:22:19.702Z: Cloning...
2024-04-23 00:22:19.733Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch "main" --depth 1 https://github.com/dotnet/aspnetcore "/var/lib/docker/codespacemount/workspace/aspnetcore"
2024-04-23 00:22:19.746Z: Cloning into '/var/lib/docker/codespacemount/workspace/aspnetcore'...
2024-04-23 00:22:26.035Z: Updating files:  65% (10226/15663)
2024-04-23 00:22:26.045Z: Updating files:  66% (10338/15663)
2024-04-23 00:22:26.059Z: Updating files:  67% (10495/15663)
2024-04-23 00:22:26.073Z: Updating files:  68% (10651/15663)
2024-04-23 00:22:26.088Z: Updating files:  69% (10808/15663)
2024-04-23 00:22:26.100Z: Updating files:  70% (10965/15663)
2024-04-23 00:22:26.123Z: Updating files:  71% (11121/15663)
2024-04-23 00:22:26.138Z: Updating files:  72% (11278/15663)
2024-04-23 00:22:26.174Z: Updating files:  73% (11434/15663)
2024-04-23 00:22:26.223Z: Updating files:  74% (11591/15663)
2024-04-23 00:22:26.235Z: Updating files:  75% (11748/15663)
2024-04-23 00:22:26.249Z: Updating files:  76% (11904/15663)
2024-04-23 00:22:26.262Z: Updating files:  77% (12061/15663)
2024-04-23 00:22:26.277Z: Updating files:  78% (12218/15663)
2024-04-23 00:22:26.290Z: Updating files:  79% (12374/15663)
2024-04-23 00:22:26.332Z: Updating files:  80% (12531/15663)
2024-04-23 00:22:26.364Z: Updating files:  81% (12688/15663)
2024-04-23 00:22:26.395Z: Updating files:  82% (12844/15663)
2024-04-23 00:22:26.408Z: Updating files:  83% (13001/15663)
2024-04-23 00:22:26.424Z: Updating files:  84% (13157/15663)
2024-04-23 00:22:26.439Z: Updating files:  85% (13314/15663)
2024-04-23 00:22:26.454Z: Updating files:  86% (13471/15663)
2024-04-23 00:22:26.471Z: Updating files:  87% (13627/15663)
2024-04-23 00:22:26.485Z: Updating files:  88% (13784/15663)
2024-04-23 00:22:26.499Z: Updating files:  89% (13941/15663)
2024-04-23 00:22:26.518Z: Updating files:  90% (14097/15663)
2024-04-23 00:22:26.535Z: Updating files:  91% (14254/15663)
2024-04-23 00:22:26.549Z: Updating files:  92% (14410/15663)
2024-04-23 00:22:26.564Z: Updating files:  93% (14567/15663)
2024-04-23 00:22:26.582Z: Updating files:  94% (14724/15663)
2024-04-23 00:22:26.593Z: Updating files:  95% (14880/15663)
2024-04-23 00:22:26.607Z: Updating files:  96% (15037/15663)
2024-04-23 00:22:26.620Z: Updating files:  97% (15194/15663)
2024-04-23 00:22:26.635Z: Updating files:  98% (15350/15663)
2024-04-23 00:22:26.647Z: Updating files:  99% (15507/15663)
2024-04-23 00:22:26.661Z: Updating files: 100% (15663/15663)
2024-04-23 00:22:26.661Z: Updating files: 100% (15663/15663), done.
2024-04-23 00:22:26.686Z: git process exited with exit code 0
2024-04-23 00:22:26.694Z: $ git -C "/var/lib/docker/codespacemount/workspace/aspnetcore" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2024-04-23 00:22:26.698Z: git process exited with exit code 0

=================================================================================
2024-04-23 00:22:26.864Z: Creating container...
2024-04-23 00:22:26.915Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/aspnetcore --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/aspnetcore/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-04-23 00:22:27.143Z: @devcontainers/cli 0.56.1. Node.js v18.19.0. linux 6.2.0-1019-azure x64.
2024-04-23 00:22:32.192Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.56.1-1713831752187/Dockerfile-with-features -t vsc-aspnetcore-345985e578c0ee1823784271e1d73d9f885f40429b85fb0bdb9a16f69fda1c8c --target dev_containers_target_stage --build-arg INSTALL_NODE=******** --build-arg NODE_VERSION=lts/* --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/aspnetcore/.devcontainer
2024-04-23 00:22:32.741Z: #0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
2024-04-23 00:22:33.002Z: #1 transferring context: 2B 0.0s done
2024-04-23 00:22:33.003Z: #1 DONE 0.4s

#2 [internal] load build definition from Dockerfile-with-features
#2 transferring dockerfile: 1.95kB done
#2 DONE 0.4s
2024-04-23 00:22:33.173Z: 
#3 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/dotnet:latest
2024-04-23 00:22:38.801Z: #3 DONE 5.8s
2024-04-23 00:22:38.996Z: 
2024-04-23 00:22:38.997Z: #4 [dev_container_auto_added_stage_label 1/2] FROM mcr.microsoft.com/vscode/devcontainers/dotnet:latest@sha256:7c3b3091f0fd089ecbffbb3131a1660caa59097a6921d6f2caad17f1abc3d56f
#4 resolve mcr.microsoft.com/vscode/devcontainers/dotnet:latest@sha256:7c3b3091f0fd089ecbffbb3131a1660caa59097a6921d6f2caad17f1abc3d56f 0.1s done
#4 sha256:03b1c0841f7200cedd5a8eaf00a8543a95a92acd0b5225ae4b935a96e4feebd2 3.73kB / 3.73kB done
#4 sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 0B / 29.12MB 0.1s
#4 sha256:7c3b3091f0fd089ecbffbb3131a1660caa59097a6921d6f2caad17f1abc3d56f 1.61kB / 1.61kB done
#4 sha256:a487f961ec6db6d8f7ddb5e2530d7ff34c3d9e00e1b7bac6c88a7b23ac1d3486 0B / 3.28kB 0.1s
#4 sha256:fadf45a0212470de35bc6a7d027a733518cbf67baa8480c53a35673a6538e45f 20.08kB / 20.08kB done
2024-04-23 00:22:39.096Z: #4 sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a 0B / 18.72MB 0.2s2024-04-23 00:22:39.096Z: 
2024-04-23 00:22:39.198Z: #4 sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 3.15MB / 29.12MB 0.3s2024-04-23 00:22:39.199Z: 
2024-04-23 00:22:39.298Z: #4 sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 14.68MB / 29.12MB 0.4s2024-04-23 00:22:39.299Z: 
2024-04-23 00:22:39.301Z: #4 sha256:a487f961ec6db6d8f7ddb5e2530d7ff34c3d9e00e1b7bac6c88a7b23ac1d3486 3.28kB / 3.28kB 0.3s done2024-04-23 00:22:39.309Z: 
2024-04-23 00:22:39.313Z: #4 sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a 1.05MB / 18.72MB 0.4s2024-04-23 00:22:39.322Z: 
2024-04-23 00:22:39.497Z: #4 sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 29.12MB / 29.12MB 0.6s2024-04-23 00:22:39.497Z: 
2024-04-23 00:22:39.498Z: #4 sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a 18.72MB / 18.72MB 0.6s2024-04-23 00:22:39.500Z: 
2024-04-23 00:22:39.501Z: #4 sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 0B / 32.23MB 0.6s2024-04-23 00:22:39.505Z: 
2024-04-23 00:22:39.615Z: #4 sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 29.12MB / 29.12MB 0.7s done
#4 sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 14.73MB / 32.23MB 0.7s
2024-04-23 00:22:39.796Z: #4 sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 29.48MB / 32.23MB 0.9s
2024-04-23 00:22:39.905Z: #4 sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a 18.72MB / 18.72MB 0.8s done
#4 sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 32.23MB / 32.23MB 1.0s
2024-04-23 00:22:39.905Z: #4 extracting sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345
#4 sha256:1764125ee6d60582da2a93872439a6170cc1f7cda6a3e446cdc9d229a2ede0d2 0B / 11.02MB 1.0s
2024-04-23 00:22:40.050Z: #4 sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 32.23MB / 32.23MB 1.0s done
2024-04-23 00:22:40.050Z: #4 sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 0B / 30.69MB 1.1s
2024-04-23 00:22:40.175Z: #4 sha256:1764125ee6d60582da2a93872439a6170cc1f7cda6a3e446cdc9d229a2ede0d2 7.34MB / 11.02MB 1.2s
#4 sha256:2900f7703f33131b08a583655daea49aaabb3922640bc9ec2f0bb47bbce0ae34 0B / 155B 1.2s
2024-04-23 00:22:40.305Z: #4 sha256:1764125ee6d60582da2a93872439a6170cc1f7cda6a3e446cdc9d229a2ede0d2 11.02MB / 11.02MB 1.3s done
#4 sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 6.53MB / 30.69MB 1.4s
#4 sha256:2900f7703f33131b08a583655daea49aaabb3922640bc9ec2f0bb47bbce0ae34 155B / 155B 1.3s done
2024-04-23 00:22:40.306Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 0B / 187.59MB 1.4s
2024-04-23 00:22:40.515Z: #4 sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 19.92MB / 30.69MB 1.5s
#4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 0B / 15.70MB 1.5s
2024-04-23 00:22:40.629Z: #4 sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 30.69MB / 30.69MB 1.7s2024-04-23 00:22:40.630Z: 
#4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 13.63MB / 187.59MB 1.7s
#4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 1.05MB / 15.70MB 1.7s
2024-04-23 00:22:40.757Z: #4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 7.34MB / 15.70MB 1.8s2024-04-23 00:22:40.760Z: 
2024-04-23 00:22:40.860Z: #4 sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 30.69MB / 30.69MB 1.8s done2024-04-23 00:22:40.862Z: 
#4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 31.46MB / 187.59MB 1.9s
#4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 13.63MB / 15.70MB 1.9s
#4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 0B / 88.07MB 1.9s
2024-04-23 00:22:40.959Z: #4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 15.70MB / 15.70MB 2.0s2024-04-23 00:22:40.962Z: 
2024-04-23 00:22:41.083Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 49.28MB / 187.59MB 2.1s
#4 sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 15.70MB / 15.70MB 2.0s done
#4 sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 0B / 32B 2.1s
2024-04-23 00:22:41.200Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 70.25MB / 187.59MB 2.3s
#4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 20.97MB / 88.07MB 2.3s
#4 sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B 2.3s done2024-04-23 00:22:41.200Z: 
2024-04-23 00:22:41.401Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 80.32MB / 187.59MB 2.4s
2024-04-23 00:22:41.403Z: #4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 30.41MB / 88.07MB 2.4s
#4 sha256:01690360f0aaad29950e8abe7f7bcb7a4b2c31af621d7b5d322f14291989a200 0B / 416B 2.4s
2024-04-23 00:22:41.505Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 98.57MB / 187.59MB 2.6s
#4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 50.33MB / 88.07MB 2.6s
2024-04-23 00:22:41.505Z: #4 sha256:01690360f0aaad29950e8abe7f7bcb7a4b2c31af621d7b5d322f14291989a200 416B / 416B 2.5s done
#4 sha256:d3c85fef10527eb3d47fb46f061961737157e376e801f1ee3a96bf83d7c162cd 0B / 134B 2.6s
2024-04-23 00:22:41.671Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 110.92MB / 187.59MB 2.7s2024-04-23 00:22:41.675Z: 
2024-04-23 00:22:41.680Z: #4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 60.33MB / 88.07MB 2.7s2024-04-23 00:22:41.685Z: 
2024-04-23 00:22:41.793Z: #4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 70.52MB / 88.07MB 2.8s
#4 sha256:d3c85fef10527eb3d47fb46f061961737157e376e801f1ee3a96bf83d7c162cd 134B / 134B 2.8s done
2024-04-23 00:22:41.905Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 133.17MB / 187.59MB 3.0s
#4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 88.07MB / 88.07MB 3.0s
#4 sha256:df18252b68552891a93f3c1cd69617f968a8138279bda30d274056aabf1e58a1 0B / 224B 3.0s
2024-04-23 00:22:42.099Z: #4 sha256:df18252b68552891a93f3c1cd69617f968a8138279bda30d274056aabf1e58a1 224B / 224B 3.2s
2024-04-23 00:22:42.210Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 145.75MB / 187.59MB 3.3s
2024-04-23 00:22:42.397Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 155.19MB / 187.59MB 3.5s
2024-04-23 00:22:42.504Z: #4 sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 88.07MB / 88.07MB 3.4s done2024-04-23 00:22:42.504Z: 
2024-04-23 00:22:42.660Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 173.02MB / 187.59MB 3.7s
2024-04-23 00:22:42.761Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 182.45MB / 187.59MB 3.8s
2024-04-23 00:22:42.986Z: #4 sha256:840794c9830e33859c9b56c4630b870c5123d4d4eb9e19c97f6b802f75bc92ff 0B / 233B 4.0s2024-04-23 00:22:42.987Z: 
2024-04-23 00:22:43.112Z: #4 sha256:df18252b68552891a93f3c1cd69617f968a8138279bda30d274056aabf1e58a1 224B / 224B 4.0s done2024-04-23 00:22:43.112Z: 
2024-04-23 00:22:43.114Z: #4 sha256:840794c9830e33859c9b56c4630b870c5123d4d4eb9e19c97f6b802f75bc92ff 233B / 233B 4.2s
2024-04-23 00:22:43.799Z: #4 sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 187.59MB / 187.59MB 4.8s done2024-04-23 00:22:43.801Z: 
2024-04-23 00:22:43.990Z: #4 extracting sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345 4.0s done2024-04-23 00:22:43.990Z: 
#4 sha256:840794c9830e33859c9b56c4630b870c5123d4d4eb9e19c97f6b802f75bc92ff 233B / 233B 4.9s done
#4 sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 0B / 7.98MB 5.0s
#4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 0B / 152.47MB 5.0s
#4 extracting sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a
2024-04-23 00:22:44.095Z: #4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 0B / 44.53MB 5.1s
2024-04-23 00:22:44.214Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 10.49MB / 152.47MB 5.3s2024-04-23 00:22:44.214Z: 
2024-04-23 00:22:44.308Z: #4 sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 1.05MB / 7.98MB 5.4s
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 3.15MB / 44.53MB 5.4s
2024-04-23 00:22:44.422Z: #4 sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 4.19MB / 7.98MB 5.5s
#4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 19.92MB / 152.47MB 5.5s
2024-04-23 00:22:44.422Z: #4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 7.34MB / 44.53MB 5.5s
2024-04-23 00:22:44.553Z: #4 sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 7.98MB / 7.98MB 5.6s
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 10.49MB / 44.53MB 5.6s2024-04-23 00:22:44.553Z: 
2024-04-23 00:22:44.665Z: #4 sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 7.98MB / 7.98MB 5.6s done
#4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 29.36MB / 152.47MB 5.7s
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 16.78MB / 44.53MB 5.7s
2024-04-23 00:22:44.833Z: #4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 20.97MB / 44.53MB 5.8s
2024-04-23 00:22:44.956Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 46.14MB / 152.47MB 6.0s
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 30.41MB / 44.53MB 6.0s2024-04-23 00:22:44.956Z: 
2024-04-23 00:22:45.096Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 57.67MB / 152.47MB 6.1s2024-04-23 00:22:45.111Z: 
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 41.94MB / 44.53MB 6.1s
2024-04-23 00:22:45.201Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 71.30MB / 152.47MB 6.3s
2024-04-23 00:22:45.201Z: #4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 44.53MB / 44.53MB 6.3s
2024-04-23 00:22:45.422Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 83.89MB / 152.47MB 6.5s
#4 sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 44.53MB / 44.53MB 6.4s done
2024-04-23 00:22:45.572Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 94.37MB / 152.47MB 6.6s
2024-04-23 00:22:45.683Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 102.76MB / 152.47MB 6.7s
2024-04-23 00:22:45.893Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 116.34MB / 152.47MB 6.9s
2024-04-23 00:22:46.008Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 137.43MB / 152.47MB 7.1s
2024-04-23 00:22:46.196Z: #4 extracting sha256:a903092de2dbe1032be255f6aa13a67ae083a3f265fd27233b508751272f445a 2.1s done
2024-04-23 00:22:46.395Z: #4 sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 152.47MB / 152.47MB 7.4s done
2024-04-23 00:22:46.547Z: #4 extracting sha256:a487f961ec6db6d8f7ddb5e2530d7ff34c3d9e00e1b7bac6c88a7b23ac1d3486 done
2024-04-23 00:22:46.591Z: #4 extracting sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff732024-04-23 00:22:46.592Z: 
2024-04-23 00:22:47.504Z: #4 extracting sha256:03ed6a6adf56f6f715105f0deee0751926934d40efc896e37dedb449be4fff73 0.8s done
2024-04-23 00:22:47.893Z: #4 extracting sha256:2900f7703f33131b08a583655daea49aaabb3922640bc9ec2f0bb47bbce0ae34
2024-04-23 00:22:48.043Z: #4 extracting sha256:2900f7703f33131b08a583655daea49aaabb3922640bc9ec2f0bb47bbce0ae34 done2024-04-23 00:22:48.045Z: 
2024-04-23 00:22:48.046Z: #4 extracting sha256:1764125ee6d60582da2a93872439a6170cc1f7cda6a3e446cdc9d229a2ede0d2
2024-04-23 00:22:48.546Z: #4 extracting sha256:1764125ee6d60582da2a93872439a6170cc1f7cda6a3e446cdc9d229a2ede0d2 0.3s done
2024-04-23 00:22:48.645Z: #4 extracting sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e
2024-04-23 00:22:50.247Z: #4 extracting sha256:fd11341df62770f82c1a47525639eac60f39d0d9690dcdc18cd98bc17fd76b3e 1.6s done
2024-04-23 00:22:50.536Z: #4 extracting sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f
2024-04-23 00:22:55.592Z: #4 extracting sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 5.1s
2024-04-23 00:22:56.383Z: #4 extracting sha256:7a3936380e1e9a612f41403125971948e725b5de22a2ac34339b50a43ea8ff0f 5.7s done
2024-04-23 00:22:57.383Z: #4 extracting sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9
2024-04-23 00:22:58.971Z: #4 extracting sha256:c092aced01925a96404610e38c62c20b40d185f344f848d7dc20ef0240636db9 1.4s done
2024-04-23 00:22:59.449Z: #4 extracting sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f
2024-04-23 00:23:01.654Z: #4 extracting sha256:d5bc3427a2b2042334c19a1da35501f28dc22f5daf28c87bb353adfe020df34f 2.1s done
2024-04-23 00:23:02.835Z: #4 extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
2024-04-23 00:23:02.961Z: #4 extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 done
#4 extracting sha256:01690360f0aaad29950e8abe7f7bcb7a4b2c31af621d7b5d322f14291989a2002024-04-23 00:23:02.963Z: 
2024-04-23 00:23:03.085Z: #4 extracting sha256:01690360f0aaad29950e8abe7f7bcb7a4b2c31af621d7b5d322f14291989a200 done
2024-04-23 00:23:03.086Z: #4 extracting sha256:d3c85fef10527eb3d47fb46f061961737157e376e801f1ee3a96bf83d7c162cd
2024-04-23 00:23:03.208Z: #4 extracting sha256:d3c85fef10527eb3d47fb46f061961737157e376e801f1ee3a96bf83d7c162cd done
#4 extracting sha256:df18252b68552891a93f3c1cd69617f968a8138279bda30d274056aabf1e58a1
2024-04-23 00:23:03.333Z: #4 extracting sha256:df18252b68552891a93f3c1cd69617f968a8138279bda30d274056aabf1e58a1 done
#4 extracting sha256:840794c9830e33859c9b56c4630b870c5123d4d4eb9e19c97f6b802f75bc92ff2024-04-23 00:23:03.334Z: 
2024-04-23 00:23:03.486Z: #4 extracting sha256:840794c9830e33859c9b56c4630b870c5123d4d4eb9e19c97f6b802f75bc92ff done2024-04-23 00:23:03.487Z: 
2024-04-23 00:23:03.552Z: #4 extracting sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef
2024-04-23 00:23:05.913Z: #4 extracting sha256:ec94c0b0968ee379ab2e84bddcda86fcc1d72cfe1ff7217a948bb79ea17c3fef 2.4s done
2024-04-23 00:23:07.067Z: #4 extracting sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1
2024-04-23 00:23:11.651Z: #4 extracting sha256:2c49bfcb538283bd3b8866357df5d7006104953a5dae68cf261e0cf32dda1cb1 4.6s done2024-04-23 00:23:11.652Z: 
2024-04-23 00:23:14.241Z: #4 extracting sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583
2024-04-23 00:23:14.905Z: #4 extracting sha256:571b80ba9173eb79cfc93bb75ac3c4bbec4652e1c4fc650dd4a53291ec06b583 0.5s done
2024-04-23 00:23:16.608Z: #4 DONE 37.8s
2024-04-23 00:23:16.768Z: 
#5 [dev_container_auto_added_stage_label 2/2] RUN if [ "********" = "********" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts/* 2>&1"; fi
2024-04-23 00:23:18.304Z: #5 1.686 Downloading and installing node v20.12.2...2024-04-23 00:23:18.305Z: 
2024-04-23 00:23:18.430Z: #5 1.812 Downloading https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-x64.tar.xz...
2024-04-23 00:23:18.560Z: #5 1.942 
       2024-04-23 00:23:18.662Z:                                                                     0.5%
#######2024-04-23 00:23:18.806Z: ##################################################                 79.8%
######################################################################## 100.0%2024-04-23 00:23:18.806Z: 
2024-04-23 00:23:18.807Z: #5 2.077 Computing checksum with sha256sum2024-04-23 00:23:18.808Z: 
2024-04-23 00:23:18.808Z: #5 2.187 Checksums matched!2024-04-23 00:23:18.809Z: 
2024-04-23 00:23:21.221Z: #5 4.602 Now using node v20.12.2 (npm v10.5.0)2024-04-23 00:23:21.221Z: 
2024-04-23 00:23:21.366Z: #5 4.748 Creating default alias: default -> lts/* (-> v20.12.2 *)
2024-04-23 00:23:22.795Z: #5 DONE 6.2s
2024-04-23 00:23:22.962Z: 
#6 preparing layers for inline cache2024-04-23 00:23:22.962Z: 
2024-04-23 00:23:25.583Z: #6 DONE 2.8s2024-04-23 00:23:25.583Z: 

#7 exporting to image
#7 exporting layers done
2024-04-23 00:23:25.818Z: #7 writing image sha256:60976257f76697171129729bb15575cbd7009c6942690a9ba036d2e507e467e8 0.0s done
#7 naming to docker.io/library/vsc-aspnetcore-345985e578c0ee1823784271e1d73d9f885f40429b85fb0bdb9a16f69fda1c8c 0.1s done
#7 DONE 0.1s
2024-04-23 00:23:25.895Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.56.1-1713831752187/Dockerfile-with-features -t vsc-aspnetcore-345985e578c0ee1823784271e1d73d9f885f40429b85fb0bdb9a16f69fda1c8c --target dev_containers_target_stage --build-arg INSTALL_NODE=******** --build-arg NODE_VERSION=lts/* --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/aspnetcore/.devcontainer
2024-04-23 00:23:25.918Z: $127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-aspnetcore-345985e578c0ee1823784271e1d73d9f885f40429b85fb0bdb9a16f69fda1c8c -c echo Container started
2024-04-23 00:23:27.148Z: Container started
2024-04-23 00:23:27.376Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/aspnetcore
2024-04-23 00:23:27.385Z: devcontainer process exited with exit code 0

=================================================================================
2024-04-23 00:23:28.637Z: Running blocking commands...
2024-04-23 00:23:28.682Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/aspnetcore --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/aspnetcore/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-04-23 00:23:28.878Z: @devcontainers/cli 0.56.1. Node.js v18.19.0. linux 6.2.0-1019-azure x64.
2024-04-23 00:23:29.081Z: Running the onCreateCommand from devcontainer.json...

2024-04-23 00:23:29.082Z: bash -i /workspaces/aspnetcore/.devcontainer/scripts/container-creation.sh
2024-04-23 00:23:29.500Z: Submodule 'src/submodules/MessagePack-CSharp' (********/aspnet/MessagePack-CSharp.git) registered for path 'src/submodules/MessagePack-CSharp'
2024-04-23 00:23:29.502Z: Submodule 'Node-Externals' (********/dotnet/Node-Externals) registered for path 'src/submodules/Node-Externals'
2024-04-23 00:23:29.504Z: Submodule 'src/submodules/googletest' (********/google/googletest) registered for path 'src/submodules/googletest'
2024-04-23 00:23:29.508Z: Cloning into '/workspaces/aspnetcore/src/submodules/MessagePack-CSharp'...
2024-04-23 00:23:31.728Z: Cloning into '/workspaces/aspnetcore/src/submodules/Node-Externals'...
2024-04-23 00:23:49.258Z: Cloning into '/workspaces/aspnetcore/src/submodules/googletest'...
2024-04-23 00:23:52.495Z: Submodule path 'src/submodules/MessagePack-CSharp': checked out 'ecc4e18ad7a0c7db51cd7e3d2997a291ed01444d'
2024-04-23 00:23:56.205Z: Submodule path 'src/submodules/Node-Externals': checked out 'fb911deddbaf7367146718374a403d393571f18a'2024-04-23 00:23:56.205Z: 
2024-04-23 00:23:56.305Z: Submodule path 'src/submodules/googletest': checked out '5a37b517ad4ab6738556f0284c256cae1466c5b4'
2024-04-23 00:23:56.356Z: warning: Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected on PATH.
2024-04-23 00:23:56.491Z: Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
2024-04-23 00:23:57.430Z:   Attempting to install 'sdk v9.0.100-preview.4.24218.26' from public_location.
2024-04-23 00:23:59.444Z: dotnet-install:(B[m Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.4.24218.26/dotnet-sdk-9.0.100-preview.4.24218.26-linux-x64.tar.gz
2024-04-23 00:24:00.093Z: curl: (22) The requested URL returned error: 404
2024-04-23 00:24:00.296Z: dotnet-install:(B[m The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.4.24218.26/dotnet-sdk-9.0.100-preview.4.24218.26-linux-x64.tar.gz' is not available.
2024-04-23 00:24:00.299Z: dotnet-install:(B[m Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.4.24218.26/dotnet-sdk-9.0.100-preview.4.24218.26-linux-x64.tar.gz
2024-04-23 00:24:02.730Z: dotnet-install:(B[m Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.4.24218.26/dotnet-sdk-9.0.100-preview.4.24218.26-linux-x64.tar.gz size is 237074729 bytes.
2024-04-23 00:24:02.731Z: dotnet-install:(B[m Extracting archive from https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.4.24218.26/dotnet-sdk-9.0.100-preview.4.24218.26-linux-x64.tar.gz
2024-04-23 00:24:11.445Z: dotnet-install:(B[m Downloaded file size is 237074729 bytes.
2024-04-23 00:24:11.445Z: dotnet-install:(B[m The remote and local file sizes are equal.
2024-04-23 00:24:11.774Z: dotnet-install:(B[m Installed version is 9.0.100-preview.4.24218.26
2024-04-23 00:24:11.788Z: dotnet-install:(B[m Adding to current process PATH: `/workspaces/aspnetcore/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install:(B[m Note that the script does not resolve dependencies during installation.
dotnet-install:(B[m To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install:(B[m Installation finished successfully.
2024-04-23 00:24:12.126Z: [?1h2024-04-23 00:24:12.138Z: [?1h2024-04-23 00:24:12.161Z: [?1h2024-04-23 00:24:12.164Z: [?1h2024-04-23 00:24:12.166Z: [?1h2024-04-23 00:24:12.168Z: [?1h2024-04-23 00:24:12.171Z: [?1h2024-04-23 00:24:12.174Z: [?1h2024-04-23 00:24:12.177Z: [?1h2024-04-23 00:24:12.284Z: [?1h2024-04-23 00:24:12.301Z: [?1h2024-04-23 00:24:12.395Z: ]9;4;3;\2024-04-23 00:24:12.428Z: [?25l[1F

<massive massive snip of garbage>

37e5c9d5a86e: Extracting  39.62MB/42.33MB
[1B2024-04-23 00:33:25.915Z: [1A[2K2024-04-23 00:33:25.917Z: 
37e5c9d5a86e: Extracting  40.47MB/42.33MB
[1B2024-04-23 00:33:25.931Z: [1A2024-04-23 00:33:25.931Z: [2K
37e5c9d5a86e: Extracting  42.33MB/42.33MB
[1B2024-04-23 00:33:26.519Z: [1A[2K
37e5c9d5a86e: 2024-04-23 00:33:26.520Z: Pull complete 
[1B2024-04-23 00:33:26.553Z: Digest: sha256:0c5b213066faec44f45c4356461413c9f2b89d57ca9672223ad0e4dd465bbcee2024-04-23 00:33:26.554Z: 
2024-04-23 00:33:26.574Z: Status: Downloaded newer image for mcr.microsoft.com/devcontainers/base:alpine
2024-04-23 00:33:26.851Z: Container started
2024-04-23 00:33:27.098Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/aspnetcore
2024-04-23 00:33:27.110Z: devcontainer process exited with exit code 0

=================================================================================
2024-04-23 00:33:30.898Z: Running blocking commands...
2024-04-23 00:33:30.941Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/aspnetcore --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/aspnetcore/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-04-23 00:33:31.241Z: @devcontainers/cli 0.56.1. Node.js v18.19.0. linux 6.2.0-1019-azure x64.
2024-04-23 00:33:31.538Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/aspnetcore
2024-04-23 00:33:31.544Z: devcontainer process exited with exit code 0

=================================================================================
2024-04-23 00:33:31.605Z: Configuring codespace...

=================================================================================
2024-04-23 00:33:31.606Z: Finished configuring codespace.
```

**Comment by wtgodbe** [comment]
I wasn't able to reproduce this issue, creating a new codespace worked fine for me. I'll leave this open in case other folks from the community are hitting similar issues & have any insight on causes/how to fix.

**Comment by jt-pt-dev** [comment]
I am seeing the same error as @PureKrome 

creation.log attached
[creation.log](https://github.com/dotnet/aspnetcore/files/15085220/creation.log)

**Comment by Vall3n** [comment]
Doesn't work for me either.
![image](https://github.com/dotnet/aspnetcore/assets/6348303/ca11b81b-f335-4375-bc12-686eb8177488)
[log.txt](https://github.com/dotnet/aspnetcore/files/15089866/log.txt)

**Comment by wtgodbe** [comment]
Ah, I see:

> [J  Npm.Workspace failed with 1 error(s)[m (17.4s)
    /workspaces/aspnetcore/eng/Npm.Workspace.nodeproj[m(32,5): error[m MSB3073[m: The command "npm ci --offline" exited with code 228.

This is related to our new NPM build approach. We're going to rework that approach in the near future, which should fix the issue for `main` - for now I recommend creating codespaces based off of `release/8.0`, which shouldn't have this issue. CC @javiercn

**Comment by PureKrome** [comment]
@wtgodbe thanks very much for looking into this again/still.

I tried it against `release/8.0` and I still get a fail. BTW, this is me doing this off the main aspnetcore _repo_ ... not a FORK of that.

[fail.log](https://github.com/dotnet/aspnetcore/files/15104591/fail.log)

**Comment by captainsafia** [comment]
@PureKrome After taking a closer look at your logs, it appears that the issue might be related to the amount of disk space configured on the container?

I see the following:

> error : An unexpected error occurred: "ENOSPC: no space left on device, mkdir '/workspaces/aspnetcore/src/SignalR/clients/ts/FunctionalTests/node_modules/@microsoft/signalr/node_modules'". [/workspaces/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests2024-04-25 05:10:08.640Z: .npmproj]

What SKU did you use for your Codespace?

**Comment by PureKrome** [comment]
SKU? I haven't bought anything? I thought it's all free for public repo's?

**Comment by wtgodbe** [comment]
@PureKrome could you try creating a new codespace with a larger build image? I've attached screnshots below on how to configure that

<img width="734" alt="Screenshot 2024-04-30 at 11 06 17 AM" src="https://github.com/dotnet/aspnetcore/assets/14283640/265641a6-18f8-4b94-8171-2f2b39f0f3cc">
<img width="973" alt="Screenshot 2024-04-30 at 11 06 32 AM" src="https://github.com/dotnet/aspnetcore/assets/14283640/1ac7745c-a13a-4ff8-b7ac-705cfe768c8c">

**Comment by PureKrome** [comment]
@wtgodbe YES! it's now working, I believe.

When i try click this one:

![image](https://github.com/dotnet/aspnetcore/assets/899878/fed1c623-e70d-4182-82b9-a9496c299c83)

it still fails.

but when i chose 8-core in the option like you had, above .. it started up with no errors reported.

**Comment by wtgodbe** [comment]
Awesome! I'll close this as complete, then. Unfortunately I don't see a why to configure the default for codespaces in the repo to be the 8-core one 😢
