### ISSUE TITLE
OpenAPI Throws `System.ArgumentNullException` Inside Docker

### ISSUE THREAD

**Issue by evanlihou** [dotnet/aspnetcore#56309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When spinning up a new Web project, then building and running in Docker, an error is thrown when attempting to go to the OpenAPI endpoint. This bug does not occur when running locally outside of a container.

### Expected Behavior

The OpenAPI document is returned, like it is when running locally in Debug/Run mode.

### Steps To Reproduce

<https://github.com/evanlihou/Net9OpenApiBugTest>

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN4FUDA16P3M", Request id "0HN4FUDA16P3M:00000001": An unhandled exception was thrown by the application.
      System.ArgumentNullException: Value cannot be null. (Parameter 'type')
         at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)
         at System.Text.Json.JsonSerializerOptions.GetTypeInfo(Type type)
         at JsonSchemaMapper.JsonSchemaMapper.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, Type parentType, JsonPropertyInfo parentPropertyInfo, ParameterInfo parentParameterInfo, String description, Boolean isNullableReferenceType, Boolean isNullableOfTElement, JsonConverter customConverter, Nullable`1 customNumberHandling, Boolean hasDefaultValue, JsonNode defaultValue, Type parentPolymorphicType, Nullable`1 typeDiscriminator)
         at JsonSchemaMapper.JsonSchemaMapper.GetJsonSchema(JsonSerializerOptions options, Type type, JsonSchemaMapperConfiguration configuration)
         at Microsoft.AspNetCore.OpenApi.OpenApiComponentService.CreateSchema(ValueTuple`2 key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.AspNetCore.OpenApi.OpenApiComponentService.GetOrCreateSchema(Type type, ApiParameterDescription parameterDescription)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponse(ApiDescription apiDescription, Int32 statusCode, ApiResponseType apiResponseType)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponses(ApiDescription description)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperation(ApiDescription description, HashSet`1 capturedTags)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperations(IGrouping`2 descriptions, HashSet`1 capturedTags)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPaths(HashSet`1 capturedTags)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### .NET Version

9.0.0-preview.6.24307.2

### Anything else?

Using latest stable version of JetBrains Rider on macOS

Using nightly `9.0-preview` Docker images as base

`dotnet --info` inside of container
```
Host:
  Version:      9.0.0-preview.6.24307.2
  Architecture: arm64
  Commit:       static
  RID:          linux-arm64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24309.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24307.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by captainsafia** [comment]
@evanlihou Thanks for reporting this issue! This is an interesting bug.

The stack trace that you've identified (and that I was able to see using your repro) is coming from the prototype implementation of the JsonSchemaExporter APIs that we used in initial iterations of our implementation and appears to be unique to enumerable types. I was not able to reproduce this with plain old `WeatherForecast`.

In recent versions of the build (9.0.0-preview.6.24324.2 and above), I'm not able to repro the same issue so I assume that this was a transient bug with the prototype that was resolved in the final implementation.

Can you verify that using a newer version of the package from the nightly feed resolves the issue for you as well?

**Comment by evanlihou** [comment]
I just pulled the latest nightly container image and it's still running 9.0.0-preview.6.24321.8 (which the error is still occurring on). I'll give it another day or two for the build you mentioned to get incorporated, then try a rebuild

**Comment by evanlihou** [comment]
Still able to repro inside of Docker with the following runtime after clearing out old images and re-pulling. If there's anything else I can do to help either make this issue more reproducible or to prove it's a non-issue, I'm happy to!

```
$ dotnet --info

Host:
  Version:      9.0.0-preview.6.24321.8
  Architecture: arm64
  Commit:       static
  RID:          linux-arm64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24324.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24321.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by captainsafia** [comment]
@evanlihou Thanks for giving this another try!

I realize I should've been clearer with my instructions. The build I was referring to earlier was the build of the `Microsoft.AspNetCore.OpenApi` package, not the .NET runtime.

Can you try out the changes in [this branch](https://github.com/captainsafia/Net9OpenApiBugTest/tree/safia/update-versions) to make sure we're on the same page? The `run.sh` script is what I used to build and run the container.

Here's the output I see from that:

<details>
<summary>http://127.0.0.1:8080/openapi/v1.json</summary>

```json
/ 20240703074318
// http://127.0.0.1:8080/openapi/v1.json

{
  "openapi": "3.0.1",
  "info": {
    "title": "Net9OpenApiBugTest | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/weatherforecast": {
      "get": {
        "tags": [
          "Net9OpenApiBugTest"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "required": [
                      "date",
                      "temperatureC",
                      "summary"
                    ],
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string",
                        "format": "date"
                      },
                      "temperatureC": {
                        "type": "integer",
                        "format": "int32"
                      },
                      "summary": {
                        "type": "string",
                        "nullable": true
                      },
                      "temperatureF": {
                        "type": "integer",
                        "format": "int32"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    
  },
  "tags": [
    {
      "name": "Net9OpenApiBugTest"
    }
  ]
}
```

</details>

**Comment by evanlihou** [comment]
Thank you for putting together that fork. I just pulled it down and yep everything seems to be working well now, so I'll close out this issue and wait for those changes to make their way to the standard Nuget feed. Have a good holiday if you're celebrating!
