### ISSUE TITLE
Generated OpenAPI docs overrides [Consumes] attribute through [FromForm]

### ISSUE THREAD

**Issue by Zylvian** [dotnet/aspnetcore#60867]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When creating a form that is expecting an image to be uploaded via `[Consumes("multipart/form-data")],` the generated OpenAPI document will define the expected value as `application/x-www-form-urlencoded`.

Controller:
```csharp
[HttpPost]
[Consumes("multipart/form-data")]
public async Task<ActionResult<SomeDto>> ImageToData(
        [FromForm] IFormFile image)
    {
    ...
```

Generated OpenAPI document:
```
...
"requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
...
```

### Expected Behavior

I expect the generated OpenAPI docs to correctly annotate the endpoint as a "multipart/form-data" endpoint, as opposed to an "application/x-www-form-urlencoded" endpoint.

### Steps To Reproduce

1. Create an AspNetCore API with generated OpenAPI documentation.
2. On a controller, add an endpoint with the [Consumes] attribute and a [FromForm] parameter.
3. Browse the generated OpenAPI document (e.g http://localhost:5211/openapi/v1.json)
4. Note the discrepancy between the Consumes attribute and the generated documentation.

### .NET Version

9.0.200

### Anything else?

ASP.NET Core: 9.0.2

`dotnet --info`

.NET SDK:
 Version:           9.0.200
 Commit:            90e8b202f2
 Workload version:  9.0.200-manifests.b4a8049f
 MSBuild version:   17.13.8+cbc39bea8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/a46039/.asdf/installs/dotnet/9.0.200/sdk/9.0.200/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.2
  Architecture: x64
  Commit:       80aa709f5d

.NET SDKs installed:
  9.0.200 [/home/a46039/.asdf/installs/dotnet/9.0.200/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.2 [/home/a46039/.asdf/installs/dotnet/9.0.200/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.2 [/home/a46039/.asdf/installs/dotnet/9.0.200/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Zylvian** [comment]
I have implemented a temporary fix, for anbody facing the same issue:

```cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi.Models;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ApiService.Utility
{
    public class MultipartFormDataOperationTransformer : IOpenApiOperationTransformer
    {
        public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context,
            CancellationToken cancellationToken)
        {
            // Retrieve the ApiDescription for the current operation
            var apiDescription = context.Description;

            // Check if the endpoint has the Consumes attribute with "multipart/form-data"
            var consumesAttribute = apiDescription.ActionDescriptor.EndpointMetadata
                .OfType<ConsumesAttribute>()
                .FirstOrDefault(attr => attr.ContentTypes.Contains("multipart/form-data"));

            if (consumesAttribute != null)
            {
                // Identify keys that are incorrectly set to 'application/x-www-form-urlencoded'
                var keysToUpdate = operation.RequestBody?.Content.Keys
                    .Where(key =>
                        key.Equals("application/x-www-form-urlencoded", System.StringComparison.OrdinalIgnoreCase))
                    .ToList();

                // Update each identified key to 'multipart/form-data'
                if (keysToUpdate != null)
                {
                    foreach (var key in keysToUpdate)
                    {
                        var mediaType = operation.RequestBody.Content[key];
                        operation.RequestBody.Content.Remove(key);
                        operation.RequestBody.Content["multipart/form-data"] = mediaType;
                    }
                }
            }

            return Task.CompletedTask;
        }
    }
}
```

`Program.cs`:
```cs
...
builder.Services.AddOpenApi(options =>
{
    options.AddOperationTransformer<MultipartFormDataOperationTransformer>();
});
...
```

**Comment by captainsafia** [comment]
I believe the root cause of this issue is related to the way MVC's model binding layer populates the model metadata for parameters that are bound from forms. The consumes attribute is processed first and overridden by the parameter-level attributes from the Form binding source.

The OpenAPI layer follows the "last one in" rules for specificity and selects the metadata added by the binding source.

We don't want to change the logic on the OpenAPI layer since that follows the general principle for metadata but we should figure out what's going on with consumes attributes vs. binding source inference here.

**Comment by kyledevans** [comment]
I ran into this issue today.  Luckily it's for a one-off project so I don't need to worry about any kind of long term solution.  That being said I did lose a few hours trying to work around this.  AI was able to help me work around the issue once I dug in and found this bug report and gave it enough information to steer it in the right direction.

Heres's the generated workaround:
```csharp
public sealed class FileUploadOperationTransformer : IOpenApiOperationTransformer
{
    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        var apiDescription = context.Description as ApiDescription;
        if (apiDescription?.ActionDescriptor is ControllerActionDescriptor controllerAction)
        {
            // Guard: only apply to POST endpoints (uploads should be POST)
            if (!string.Equals(apiDescription.HttpMethod, "POST", StringComparison.OrdinalIgnoreCase))
            {
                return Task.CompletedTask;
            }

            // Collect method parameters and exclude CancellationToken (it shouldn't count as an API surface parameter)
            var methodParameters = controllerAction.MethodInfo.GetParameters();
            var nonCancellationParameters = methodParameters
                .Where(p => p.ParameterType != typeof(CancellationToken))
                .ToArray();

            var fileParameters = nonCancellationParameters
                .Where(p => p.ParameterType == typeof(IFormFile))
                .ToArray();

            // Apply transformation only when the shape is unambiguous: a single file parameter
            if (nonCancellationParameters.Length == 1 && fileParameters.Length == 1)
            {
                var fileParamName = fileParameters[0].Name ?? "file";

                // Replace the autogenerated request body with a succinct multipart/form-data model
                operation.RequestBody = new OpenApiRequestBody
                {
                    Content = new Dictionary<string, OpenApiMediaType>
                    {
                        ["multipart/form-data"] = new OpenApiMediaType
                        {
                            Schema = new OpenApiSchema
                            {
                                Type = "object",
                                Properties = new Dictionary<string, OpenApiSchema>
                                {
                                    [fileParamName] = new OpenApiSchema
                                    {
                                        Type = "string",
                                        Format = "binary"
                                    }
                                },
                                Required = new HashSet<string> { fileParamName }
                            }
                        }
                    }
                };
            }
        }

        return Task.CompletedTask;
    }
}
```

And Program.cs:
```csharp
builder.Services.AddOpenApi(options =>
{
    options.AddOperationTransformer(new FileUploadOperationTransformer());
});
```

Hopefully the workaround is helpful for others.

**Comment by SaebAmini** [comment]
Seems to be resolved as of `10.0.5`

**Comment by mikekistler** [comment]
@SaebAmini I just tried to confirm your findings but actually found the opposite. In my tests the problem still repro's in 10.0.5. Can you please double check?

**Comment by SaebAmini** [comment]
@mikekistler these are the versions I'm on:

```
<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />

<PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
</PropertyGroup>

<PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.5">
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	<PrivateAssets>all</PrivateAssets>
</PackageReference>
```

After adding `Consumes("multipart/form-data")` to an MVC endpoint, this is what gets generated:

```
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
```

When removed, it reverts to `application/x-www-form-urlencoded`. Apologies I won't have time to dig further into why.

**Comment by NinovanderMark** [comment]
I'm getting this same issue on version 10.0.5.
```
<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
```

These are the annotations on the controller method.
```
[HttpPut("{id}/content")]
[Consumes("multipart/form-data")]
[ProducesResponseType<ProblemDetails>(401)]
[ProducesResponseType<ProblemDetails>(404)]
[ProducesResponseType(200)]
public async Task<IActionResult> UploadAssetContent(long id, [FromForm] IFormFile file)
```

Which generates the following in the spec.
```
"requestBody": {
    "content": {
      "application/x-www-form-urlencoded": {
        "schema": {
          "type": "object",
```

**Comment by NinovanderMark** [comment]
I've created a minimal reproducible project that demonstrates this still doesn't work with package version `10.0.6`.

https://github.com/NinovanderMark/Repro-ConsumesOverrideOpenApi
